import type { SermonFullLines, SermonLang } from '../types'

export type FullPack = Record<SermonLang, SermonFullLines>

export const CALL_FULL: Record<string, FullPack> = {
  'obedience': {
    en: {
        title: ['If Ye Love Me, Keep My Commandments', 'Love That Shows Up as Obedience'],
        bigIdea: ['Name it.', 'Jesus’ message is direct: if ye love me, keep my commandments.'],
        openingHook: ['Love for Jesus shows up as obedience. This is not a lecture for somebody else. It is for the week you actually have.', 'If ye love me, keep my commandments. He already joined the two. This is not a lecture for somebody else. It is for the week you actually have.'],
        context: ['Jesus is preparing the disciples for his leaving. He doesn’t separate affection from commands. If ye love me, keep my commandments. Love here isn’t a song we feel. It’s a life that does what he said. That is why this passage still belongs in a class that wants more than a slogan.', 'John 14 puts love where you can see it. Not in the volume of the singing. In the keeping. He is about to go to the cross, and he tells them what love looks like on this side of it. That is why this passage still belongs in a class that wants more than a slogan.'],
        points: [
          { heading: ['Hear what God already said', 'Start with the Word, not the week'], thought: ['Love for Jesus shows up as obedience. That line is not a slogan. It is the doorway into the text.', 'If ye love me, keep my commandments. He already joined the two. That line is not a slogan. It is the doorway into the text.'] },
          { heading: ['See where the passage sits', 'The story behind the sentence'], thought: ['Jesus is preparing the disciples for his leaving. Stay there long enough for the room to quiet down.', 'John 14 puts love where you can see it. Stay there long enough for the room to quiet down.'] },
          { heading: ['Take the next obedient step', 'Leave with one clear yes'], thought: ['Name it. Do it this week. Let love be visible where it has only been a sentence.', 'Jesus’ message is direct: if ye love me, keep my commandments. Don’t leave love as a feeling.'] },
        ],
        application: ['Most of us say we love him and then negotiate the verses that cost us. When it’s inconvenient. When nobody will check. When we already have an explanation. Selective obedience is selective love. Keeping his commandments doesn’t earn him. It’s the evidence that we are his. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.', 'Admiring a command is not the same as doing it. The verse you explain away is the one that would have made love visible. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.'],
        invitation: ['Brothers, come. Which commandment are you admiring instead of keeping? Forgiveness. Purity. Truth in your speech. Maybe the one you already know and keep postponing. If the Spirit is pressing you, do not wait for a better feeling. Answer him.', 'Brothers, come. How would this class know that you love him if they watched your week? Not your explanation. Your week. If the Spirit is pressing you, do not wait for a better feeling. Answer him.'],
        closingPrayer: ['Father, thank you for your Word. Plant this truth in us for the week we actually have. Give us courage to obey and mercy when we fail. Through Jesus Christ. Amen.', 'Lord, we have heard you. Now keep us from leaving this room unchanged. Make us doers of the Word. In Jesus’ name. Amen.'],
        questions: [
          [
            'What command of Jesus have you explained away?',
            'How would this class know that you love him if they watched your week?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
          [
            'Where is obedience still waiting until it feels like love?',
            'What one command will you keep before the week is over?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
        ],
      },
    es: {
        title: ['Si me amáis, guardad mis mandamientos', 'Amor que se ve en la obediencia'],
        bigIdea: ['Nómbralo.', 'El mensaje de Jesús es directo: si me amáis, guardad mis mandamientos.'],
        openingHook: ['El amor a Jesús se ve en la obediencia. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.', 'Si me amáis, guardad mis mandamientos. Él ya unió las dos cosas. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.'],
        context: ['Jesús prepara a los discípulos para su partida. No separa el afecto de los mandamientos. Si me amáis, guardad mis mandamientos. El amor aquí no es una canción que sentimos. Es una vida que hace lo que él dijo. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.', 'Juan 14 pone el amor donde se puede ver. No en el volumen del canto. En el guardar. Está por ir a la cruz, y les dice cómo se ve el amor de este lado. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.'],
        points: [
          { heading: ['Oye lo que Dios ya dijo', 'Empieza con la Palabra, no con la semana'], thought: ['El amor a Jesús se ve en la obediencia. Esa línea no es un lema. Es la puerta al texto.', 'Si me amáis, guardad mis mandamientos. Él ya unió las dos cosas. Esa línea no es un lema. Es la puerta al texto.'] },
          { heading: ['Mira dónde se asienta el pasaje', 'La historia detrás de la frase'], thought: ['Jesús prepara a los discípulos para su partida. Quédate ahí el tiempo suficiente para que el cuarto se calle.', 'Juan 14 pone el amor donde se puede ver. Quédate ahí el tiempo suficiente para que el cuarto se calle.'] },
          { heading: ['Da el siguiente paso de obediencia', 'Sal con un sí claro'], thought: ['Nómbralo. Hazlo esta semana. Que el amor se vea donde solo ha sido una frase.', 'El mensaje de Jesús es directo: si me amáis, guardad mis mandamientos. No dejes el amor como un sentimiento.'] },
        ],
        application: ['Casi todos decimos que lo amamos y luego negociamos los versículos que nos cuestan. Cuando es incómodo. Cuando nadie va a revisar. Cuando ya tenemos una explicación. Una obediencia selectiva es un amor selectivo. Guardar sus mandamientos no lo gana. Es la evidencia de que somos suyos. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.', 'Admirar un mandamiento no es lo mismo que hacerlo. El versículo que explicas para no hacerlo es el que habría hecho visible el amor. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.'],
        invitation: ['Hermanos, vengan. ¿Qué mandamiento estás admirando en vez de guardarlo? El perdón. La pureza. La verdad en tu habla. Quizás el que ya conoces y sigues aplazando. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.', 'Hermanos, vengan. ¿Cómo sabría esta clase que lo amas si mirara tu semana? No tu explicación. Tu semana. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.'],
        closingPrayer: ['Padre, gracias por tu Palabra. Siembra esta verdad en nosotros para la semana que de verdad tenemos. Danos valor para obedecer y misericordia cuando fallemos. Por Jesucristo. Amén.', 'Señor, te hemos oído. Ahora no dejes que salgamos de este cuarto sin cambio. Haznos hacedores de la Palabra. En el nombre de Jesús. Amén.'],
        questions: [
          [
            '¿Qué mandamiento de Jesús has explicado para no hacerlo?',
            '¿Cómo sabría esta clase que lo amas si mirara tu semana?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
          [
            '¿Dónde la obediencia sigue esperando hasta que se sienta como amor?',
            '¿Qué mandamiento vas a guardar antes de que acabe la semana?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
        ],
      },
    pt: {
        title: ['Se me amais, guardai os meus mandamentos', 'Amor que aparece como obediência'],
        bigIdea: ['Nomeie.', 'A mensagem de Jesus é direta: se me amais, guardai os meus mandamentos.'],
        openingHook: ['O amor a Jesus aparece na obediência. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.', 'Se me amais, guardai os meus mandamentos. Ele já uniu as duas coisas. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.'],
        context: ['Jesus prepara os discípulos para a sua partida. Ele não separa o afeto dos mandamentos. Se me amais, guardai os meus mandamentos. O amor aqui não é uma canção que sentimos. É uma vida que faz o que ele disse. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.', 'João 14 põe o amor onde se pode ver. Não no volume do canto. No guardar. Ele está para ir à cruz, e diz como o amor aparece deste lado. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.'],
        points: [
          { heading: ['Ouça o que Deus já disse', 'Comece pela Palavra, não pela semana'], thought: ['O amor a Jesus aparece na obediência. Essa linha não é um lema. É a porta para o texto.', 'Se me amais, guardai os meus mandamentos. Ele já uniu as duas coisas. Essa linha não é um lema. É a porta para o texto.'] },
          { heading: ['Veja onde a passagem se assenta', 'A história por trás da frase'], thought: ['Jesus prepara os discípulos para a sua partida. Fique ali tempo bastante para a sala se aquietar.', 'João 14 põe o amor onde se pode ver. Fique ali tempo bastante para a sala se aquietar.'] },
          { heading: ['Dê o próximo passo de obediência', 'Saia com um sim claro'], thought: ['Nomeie. Faça nesta semana. Que o amor se veja onde só tem sido uma frase.', 'A mensagem de Jesus é direta: se me amais, guardai os meus mandamentos. Não deixe o amor como um sentimento.'] },
        ],
        application: ['Quase todos dizemos que o amamos e depois negociamos os versículos que nos custam. Quando é incômodo. Quando ninguém vai conferir. Quando já temos uma explicação. Uma obediência seletiva é um amor seletivo. Guardar os mandamentos dele não o ganha. É a evidência de que somos dele. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.', 'Admirar um mandamento não é a mesma coisa que cumpri-lo. O versículo que você explica para não cumprir é o que teria feito o amor visível. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.'],
        invitation: ['Irmãos, venham. Que mandamento você está admirando em vez de guardar? O perdão. A pureza. A verdade na sua fala. Talvez aquele que você já conhece e continua adiando. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.', 'Irmãos, venham. Como esta classe saberia que você o ama se olhasse a sua semana? Não a sua explicação. A sua semana. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.'],
        closingPrayer: ['Pai, obrigado pela tua Palavra. Planta esta verdade em nós para a semana que de fato temos. Dá-nos coragem para obedecer e misericórdia quando falharmos. Por Jesus Cristo. Amém.', 'Senhor, nós te ouvimos. Agora não nos deixes sair desta sala sem mudança. Faz-nos praticantes da Palavra. Em nome de Jesus. Amém.'],
        questions: [
          [
            'Que mandamento de Jesus você explicou para não cumprir?',
            'Como esta classe saberia que você o ama se olhasse a sua semana?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
          [
            'Onde a obediência ainda espera até parecer amor?',
            'Que mandamento você vai guardar antes de a semana acabar?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
        ],
      },
  },
  'word': {
    en: {
        title: ['A Lamp Unto My Feet', 'Open the Book Before the Next Step'],
        bigIdea: ['Open it today.', 'The psalm’s message is direct: his word is a lamp for the feet.'],
        openingHook: ['The Word is a lamp, not a souvenir. This is not a lecture for somebody else. It is for the week you actually have.', 'A closed book cannot light the next step. This is not a lecture for somebody else. It is for the week you actually have.'],
        context: ['Psalm 119 is a long love for what God has said. Thy word is a lamp unto my feet, and a light unto my path. It shows the next step. It is not a floodlight for the whole decade, and it does not flatter the traveler. That is why this passage still belongs in a class that wants more than a slogan.', 'The psalm assumes a person who keeps the word near enough to walk by. Light is for obedience. Not for winning an argument and then living unchanged. That is why this passage still belongs in a class that wants more than a slogan.'],
        points: [
          { heading: ['Hear what God already said', 'Start with the Word, not the week'], thought: ['The Word is a lamp, not a souvenir. That line is not a slogan. It is the doorway into the text.', 'A closed book cannot light the next step. That line is not a slogan. It is the doorway into the text.'] },
          { heading: ['See where the passage sits', 'The story behind the sentence'], thought: ['Psalm 119 is a long love for what God has said. Stay there long enough for the room to quiet down.', 'The psalm assumes a person who keeps the word near enough to walk by. Stay there long enough for the room to quiet down.'] },
          { heading: ['Take the next obedient step', 'Leave with one clear yes'], thought: ['Open it today. Take the step it shows. Don’t leave the lamp on the shelf.', 'The psalm’s message is direct: his word is a lamp for the feet. Use it on the road you’re actually walking.'] },
        ],
        application: ['Most of us honor the Bible and then walk by instinct. When I already know what I want. When the room agrees. When opening it would slow me down. We put the lamp on the shelf. God doesn’t work that way. The next step is in what he already said. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.', 'A verse you will not obey is not yet a lamp. It’s a quote. Take the step it shows. Don’t ask it to shine and then walk in the ditch. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.'],
        invitation: ['Brothers, come. When did you last let a verse decide your next step? This morning. Last month. You can’t remember. Maybe you wanted the lamp for the argument, not for the feet. If the Spirit is pressing you, do not wait for a better feeling. Answer him.', 'Brothers, come. Where are you walking by your own light? The decision. The grudge. The habit. Open the book before you take the step. If the Spirit is pressing you, do not wait for a better feeling. Answer him.'],
        closingPrayer: ['Father, thank you for your Word. Plant this truth in us for the week we actually have. Give us courage to obey and mercy when we fail. Through Jesus Christ. Amen.', 'Lord, we have heard you. Now keep us from leaving this room unchanged. Make us doers of the Word. In Jesus’ name. Amen.'],
        questions: [
          [
            'Where are you walking by your own light?',
            'What verse is already clear, and still unobeyed?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
          [
            'When did a verse last change what you did the same day?',
            'What step is the lamp already showing that you keep postponing?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
        ],
      },
    es: {
        title: ['Lámpara es a mis pies', 'Abre el libro antes del siguiente paso'],
        bigIdea: ['Ábrela hoy.', 'El mensaje del salmo es directo: su palabra es lámpara a los pies.'],
        openingHook: ['La Palabra es lámpara, no un recuerdo. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.', 'Un libro cerrado no puede alumbrar el siguiente paso. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.'],
        context: ['El Salmo 119 es un amor largo a lo que Dios ha dicho. Lámpara es a mis pies tu palabra, y lumbrera a mi camino. Muestra el siguiente paso. No es un reflector para toda la década, y no adula al que camina. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.', 'El salmo supone una persona que tiene la palabra bastante cerca para caminar por ella. La luz es para obedecer. No es para ganar una discusión y seguir igual. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.'],
        points: [
          { heading: ['Oye lo que Dios ya dijo', 'Empieza con la Palabra, no con la semana'], thought: ['La Palabra es lámpara, no un recuerdo. Esa línea no es un lema. Es la puerta al texto.', 'Un libro cerrado no puede alumbrar el siguiente paso. Esa línea no es un lema. Es la puerta al texto.'] },
          { heading: ['Mira dónde se asienta el pasaje', 'La historia detrás de la frase'], thought: ['El Salmo 119 es un amor largo a lo que Dios ha dicho. Quédate ahí el tiempo suficiente para que el cuarto se calle.', 'El salmo supone una persona que tiene la palabra bastante cerca para caminar por ella. Quédate ahí el tiempo suficiente para que el cuarto se calle.'] },
          { heading: ['Da el siguiente paso de obediencia', 'Sal con un sí claro'], thought: ['Ábrela hoy. Da el paso que muestra. No dejes la lámpara en el estante.', 'El mensaje del salmo es directo: su palabra es lámpara a los pies. Úsala en el camino que de veras estás caminando.'] },
        ],
        application: ['Casi todos honramos la Biblia y luego caminamos por instinto. Cuando ya sé lo que quiero. Cuando el cuarto está de acuerdo. Cuando abrirla me atrasaría. Dejamos la lámpara en el estante. Dios no funciona así. El siguiente paso está en lo que él ya dijo. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.', 'Un versículo que no vas a obedecer todavía no es lámpara. Es una cita. Da el paso que muestra. No le pidas que alumbre y luego camines por la zanja. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.'],
        invitation: ['Hermanos, vengan. ¿Cuándo fue la última vez que un versículo decidió tu siguiente paso? Esta mañana. El mes pasado. No te acuerdas. Quizás querías la lámpara para la discusión, no para los pies. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.', 'Hermanos, vengan. ¿Dónde estás caminando con tu propia luz? La decisión. El rencor. El hábito. Abre el libro antes de dar el paso. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.'],
        closingPrayer: ['Padre, gracias por tu Palabra. Siembra esta verdad en nosotros para la semana que de verdad tenemos. Danos valor para obedecer y misericordia cuando fallemos. Por Jesucristo. Amén.', 'Señor, te hemos oído. Ahora no dejes que salgamos de este cuarto sin cambio. Haznos hacedores de la Palabra. En el nombre de Jesús. Amén.'],
        questions: [
          [
            '¿Dónde estás caminando con tu propia luz?',
            '¿Qué versículo ya está claro, y sigue sin obedecerse?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
          [
            '¿Cuándo un versículo cambió por última vez lo que hiciste el mismo día?',
            '¿Qué paso ya está mostrando la lámpara, y sigues aplazando?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
        ],
      },
    pt: {
        title: ['Lâmpada para os meus pés', 'Abra o livro antes do próximo passo'],
        bigIdea: ['Abra hoje.', 'A mensagem do salmo é direta: a palavra dele é lâmpada para os pés.'],
        openingHook: ['A Palavra é lâmpada, não uma lembrança. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.', 'Um livro fechado não alumia o próximo passo. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.'],
        context: ['O Salmo 119 é um amor longo ao que Deus disse. Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho. Mostra o próximo passo. Não é um holofote para a década inteira, e não elogia o viajante. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.', 'O salmo supõe uma pessoa que mantém a palavra perto o bastante para andar por ela. A luz é para a obediência. Não é para ganhar uma discussão e seguir igual. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.'],
        points: [
          { heading: ['Ouça o que Deus já disse', 'Comece pela Palavra, não pela semana'], thought: ['A Palavra é lâmpada, não uma lembrança. Essa linha não é um lema. É a porta para o texto.', 'Um livro fechado não alumia o próximo passo. Essa linha não é um lema. É a porta para o texto.'] },
          { heading: ['Veja onde a passagem se assenta', 'A história por trás da frase'], thought: ['O Salmo 119 é um amor longo ao que Deus disse. Fique ali tempo bastante para a sala se aquietar.', 'O salmo supõe uma pessoa que mantém a palavra perto o bastante para andar por ela. Fique ali tempo bastante para a sala se aquietar.'] },
          { heading: ['Dê o próximo passo de obediência', 'Saia com um sim claro'], thought: ['Abra hoje. Dê o passo que ela mostra. Não deixe a lâmpada na prateleira.', 'A mensagem do salmo é direta: a palavra dele é lâmpada para os pés. Use-a na estrada que você de fato está andando.'] },
        ],
        application: ['Quase todos honramos a Bíblia e depois andamos por instinto. Quando eu já sei o que quero. Quando a sala concorda. Quando abri-la me atrasaria. Deixamos a lâmpada na prateleira. Deus não trabalha assim. O próximo passo está no que ele já disse. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.', 'Um versículo que você não vai obedecer ainda não é lâmpada. É uma citação. Dê o passo que ela mostra. Não peça que alumie e depois ande na vala. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.'],
        invitation: ['Irmãos, venham. Quando foi a última vez que um versículo decidiu o seu próximo passo? Hoje de manhã. Mês passado. Você não lembra. Talvez você quisesse a lâmpada para a discussão, não para os pés. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.', 'Irmãos, venham. Onde você está andando com a sua própria luz? A decisão. O rancor. O hábito. Abra o livro antes de dar o passo. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.'],
        closingPrayer: ['Pai, obrigado pela tua Palavra. Planta esta verdade em nós para a semana que de fato temos. Dá-nos coragem para obedecer e misericórdia quando falharmos. Por Jesus Cristo. Amém.', 'Senhor, nós te ouvimos. Agora não nos deixes sair desta sala sem mudança. Faz-nos praticantes da Palavra. Em nome de Jesus. Amém.'],
        questions: [
          [
            'Onde você está andando com a sua própria luz?',
            'Que versículo já está claro, e continua sem obediência?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
          [
            'Quando um versículo mudou pela última vez o que você fez no mesmo dia?',
            'Que passo a lâmpada já está mostrando, e você continua adiando?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
        ],
      },
  },
  'service': {
    en: {
        title: ['The Son of Man Came to Serve', 'Greatness Looks Like a Towel'],
        bigIdea: ['Find one unimpressive task and do it as he did.', 'Jesus’ message is direct: the Son of man came to minister, and to give his life a ransom.'],
        openingHook: ['The Son of Man came to serve, and to give his life. This is not a lecture for somebody else. It is for the week you actually have.', 'Greatness in this room looks like a towel, not a seat. This is not a lecture for somebody else. It is for the week you actually have.'],
        context: ['James and John want seats of glory. Jesus tells the twelve that greatness will not look like the rulers of the Gentiles. Whoever will be great must be a servant. Then he points to himself. The Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many. That is why this passage still belongs in a class that wants more than a slogan.', 'The request was for thrones. The answer was a ransom. Service in the church is shaped by a cross, not by a platform. That is why this passage still belongs in a class that wants more than a slogan.'],
        points: [
          { heading: ['Hear what God already said', 'Start with the Word, not the week'], thought: ['The Son of Man came to serve, and to give his life. That line is not a slogan. It is the doorway into the text.', 'Greatness in this room looks like a towel, not a seat. That line is not a slogan. It is the doorway into the text.'] },
          { heading: ['See where the passage sits', 'The story behind the sentence'], thought: ['James and John want seats of glory. Stay there long enough for the room to quiet down.', 'The request was for thrones. Stay there long enough for the room to quiet down.'] },
          { heading: ['Take the next obedient step', 'Leave with one clear yes'], thought: ['Find one unimpressive task and do it as he did. Don’t announce it.', 'Jesus’ message is direct: the Son of man came to minister, and to give his life a ransom. Follow that shape.'] },
        ],
        application: ['Most of us want the name of ministry and the feel of being needed. When the seat is visible. When the work is thanked. When the towel is somebody else’s. Jesus defines service by a ransom. The church is healthiest when her people take the lower place on purpose. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.', 'An unimpressive task is the test. The chairs. The visit nobody posts. The mess. Do it as he did, without announcing it. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.'],
        invitation: ['Brothers, come. Are you asking to be served by this church, or have you come to serve? The seat. The towel. You already know which one you’ve been reaching for. If the Spirit is pressing you, do not wait for a better feeling. Answer him.', 'Brothers, come. Where do you still want the seat more than the towel? Name it. Then take the lower place this week. If the Spirit is pressing you, do not wait for a better feeling. Answer him.'],
        closingPrayer: ['Father, thank you for your Word. Plant this truth in us for the week we actually have. Give us courage to obey and mercy when we fail. Through Jesus Christ. Amen.', 'Lord, we have heard you. Now keep us from leaving this room unchanged. Make us doers of the Word. In Jesus’ name. Amen.'],
        questions: [
          [
            'Where do you still want the seat more than the towel?',
            'Who would be helped if you took the lower place on purpose?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
          [
            'What task have you been leaving for someone else because it doesn’t show?',
            'How is a ransom different from a platform?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
        ],
      },
    es: {
        title: ['El Hijo del Hombre vino para servir', 'La grandeza se parece a una toalla'],
        bigIdea: ['Halla una tarea sin brillo y hazla como él.', 'El mensaje de Jesús es directo: el Hijo del hombre vino para servir, y para dar su vida en rescate.'],
        openingHook: ['El Hijo del Hombre vino a servir, y a dar su vida. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.', 'La grandeza en este cuarto se parece a una toalla, no a un asiento. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.'],
        context: ['Jacobo y Juan quieren asientos de gloria. Jesús dice a los doce que la grandeza no se parecerá a los príncipes de los gentiles. El que quiera ser grande será servidor. Luego se señala. El Hijo del hombre no vino para ser servido, sino para servir, y para dar su vida en rescate por muchos. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.', 'El pedido era de tronos. La respuesta fue un rescate. El servicio en la iglesia tiene forma de cruz, no de plataforma. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.'],
        points: [
          { heading: ['Oye lo que Dios ya dijo', 'Empieza con la Palabra, no con la semana'], thought: ['El Hijo del Hombre vino a servir, y a dar su vida. Esa línea no es un lema. Es la puerta al texto.', 'La grandeza en este cuarto se parece a una toalla, no a un asiento. Esa línea no es un lema. Es la puerta al texto.'] },
          { heading: ['Mira dónde se asienta el pasaje', 'La historia detrás de la frase'], thought: ['Jacobo y Juan quieren asientos de gloria. Quédate ahí el tiempo suficiente para que el cuarto se calle.', 'El pedido era de tronos. Quédate ahí el tiempo suficiente para que el cuarto se calle.'] },
          { heading: ['Da el siguiente paso de obediencia', 'Sal con un sí claro'], thought: ['Halla una tarea sin brillo y hazla como él. No la anuncies.', 'El mensaje de Jesús es directo: el Hijo del hombre vino para servir, y para dar su vida en rescate. Sigue esa forma.'] },
        ],
        application: ['Casi todos queremos el nombre del ministerio y la sensación de que nos necesitan. Cuando el asiento se ve. Cuando el trabajo se agradece. Cuando la toalla es de otro. Jesús define el servicio por un rescate. La iglesia está más sana cuando su gente toma el lugar bajo a propósito. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.', 'Una tarea sin brillo es la prueba. Las sillas. La visita que nadie publica. El desorden. Hazla como él, sin anunciarla. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.'],
        invitation: ['Hermanos, vengan. ¿Estás pidiendo que esta iglesia te sirva, o viniste a servir? El asiento. La toalla. Ya sabes cuál has estado buscando. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.', 'Hermanos, vengan. ¿Dónde todavía quieres el asiento más que la toalla? Nómbralo. Luego toma el lugar bajo esta semana. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.'],
        closingPrayer: ['Padre, gracias por tu Palabra. Siembra esta verdad en nosotros para la semana que de verdad tenemos. Danos valor para obedecer y misericordia cuando fallemos. Por Jesucristo. Amén.', 'Señor, te hemos oído. Ahora no dejes que salgamos de este cuarto sin cambio. Haznos hacedores de la Palabra. En el nombre de Jesús. Amén.'],
        questions: [
          [
            '¿Dónde todavía quieres el asiento más que la toalla?',
            '¿A quién ayudarías si tomaras el lugar bajo a propósito?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
          [
            '¿Qué tarea has estado dejando para otro porque no se ve?',
            '¿En qué se diferencia un rescate de una plataforma?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
        ],
      },
    pt: {
        title: ['O Filho do Homem veio para servir', 'A grandeza parece uma toalha'],
        bigIdea: ['Ache uma tarefa sem brilho e faça-a como ele.', 'A mensagem de Jesus é direta: o Filho do homem veio para servir, e para dar a sua vida em resgate.'],
        openingHook: ['O Filho do Homem veio para servir, e para dar a sua vida. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.', 'A grandeza nesta sala parece uma toalha, não um assento. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.'],
        context: ['Tiago e João querem assentos de glória. Jesus diz aos doze que a grandeza não vai parecer a dos príncipes dos gentios. Quem quiser ser grande será servo. Depois aponta para si. O Filho do homem não veio para ser servido, mas para servir, e para dar a sua vida em resgate de muitos. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.', 'O pedido era de tronos. A resposta foi um resgate. O serviço na igreja tem forma de cruz, não de palco. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.'],
        points: [
          { heading: ['Ouça o que Deus já disse', 'Comece pela Palavra, não pela semana'], thought: ['O Filho do Homem veio para servir, e para dar a sua vida. Essa linha não é um lema. É a porta para o texto.', 'A grandeza nesta sala parece uma toalha, não um assento. Essa linha não é um lema. É a porta para o texto.'] },
          { heading: ['Veja onde a passagem se assenta', 'A história por trás da frase'], thought: ['Tiago e João querem assentos de glória. Fique ali tempo bastante para a sala se aquietar.', 'O pedido era de tronos. Fique ali tempo bastante para a sala se aquietar.'] },
          { heading: ['Dê o próximo passo de obediência', 'Saia com um sim claro'], thought: ['Ache uma tarefa sem brilho e faça-a como ele. Não anuncie.', 'A mensagem de Jesus é direta: o Filho do homem veio para servir, e para dar a sua vida em resgate. Siga essa forma.'] },
        ],
        application: ['Quase todos queremos o nome do ministério e a sensação de ser necessários. Quando o assento aparece. Quando o trabalho é agradecido. Quando a toalha é de outro. Jesus define o serviço por um resgate. A igreja está mais sã quando o seu povo toma o lugar baixo de propósito. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.', 'Uma tarefa sem brilho é a prova. As cadeiras. A visita que ninguém publica. A bagunça. Faça-a como ele, sem anunciá-la. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.'],
        invitation: ['Irmãos, venham. Você está pedindo que esta igreja o sirva, ou veio para servir? O assento. A toalha. Você já sabe qual tem buscado. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.', 'Irmãos, venham. Onde você ainda quer o assento mais que a toalha? Nomeie. Depois tome o lugar baixo nesta semana. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.'],
        closingPrayer: ['Pai, obrigado pela tua Palavra. Planta esta verdade em nós para a semana que de fato temos. Dá-nos coragem para obedecer e misericórdia quando falharmos. Por Jesus Cristo. Amém.', 'Senhor, nós te ouvimos. Agora não nos deixes sair desta sala sem mudança. Faz-nos praticantes da Palavra. Em nome de Jesus. Amém.'],
        questions: [
          [
            'Onde você ainda quer o assento mais que a toalha?',
            'Quem seria ajudado se você tomasse o lugar baixo de propósito?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
          [
            'Que tarefa você tem deixado para outro porque não aparece?',
            'Em que um resgate é diferente de um palco?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
        ],
      },
  },
  'identity': {
    en: {
        title: ['A New Creature in Christ', 'The Old Verdict Is Not Your Name'],
        bigIdea: ['Say who you are in Christ, from this verse, before you rehearse who you were.', 'Paul’s message is direct: in Christ, a new creature.'],
        openingHook: ['In Christ, the old verdict is not the last word. This is not a lecture for somebody else. It is for the week you actually have.', 'If any man be in Christ, he is a new creature. Old things are passed away. This is not a lecture for somebody else. It is for the week you actually have.'],
        context: ['Paul is explaining why believers no longer live unto themselves. The newness isn’t a personality upgrade. It’s a new standing, because Christ died and rose, and the person is in him. Old things are passed away. Behold, all things are become new. That is why this passage still belongs in a class that wants more than a slogan.', '2 Corinthians 5 ties the new creature to the cross. He died for all, that they which live should not henceforth live unto themselves. The name changes because the standing changed. That is why this passage still belongs in a class that wants more than a slogan.'],
        points: [
          { heading: ['Hear what God already said', 'Start with the Word, not the week'], thought: ['In Christ, the old verdict is not the last word. That line is not a slogan. It is the doorway into the text.', 'If any man be in Christ, he is a new creature. Old things are passed away. That line is not a slogan. It is the doorway into the text.'] },
          { heading: ['See where the passage sits', 'The story behind the sentence'], thought: ['Paul is explaining why believers no longer live unto themselves. Stay there long enough for the room to quiet down.', '2 Corinthians 5 ties the new creature to the cross. Stay there long enough for the room to quiet down.'] },
          { heading: ['Take the next obedient step', 'Leave with one clear yes'], thought: ['Say who you are in Christ, from this verse, before you rehearse who you were. Then live the week as that person.', 'Paul’s message is direct: in Christ, a new creature. The old verdict is not your name.'] },
        ],
        application: ['Most of us introduce ourselves by the old failure and then wonder why we live there. When I rehearse the old name. When I negotiate with a sin as if Christ had not made me new. The verse doesn’t deny the past. It refuses to let the past be your name. A new creature still repents. He doesn’t move back into the old verdict. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.', 'The knock of the old life is real. Answering to it is a choice. Say who you are in Christ before you rehearse who you were. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.'],
        invitation: ['Brothers, come. What old name are you still answering to? The failure. The label somebody gave you. The sin you’ve started calling your personality. Maybe a verdict you keep reading after Christ tore it up. If the Spirit is pressing you, do not wait for a better feeling. Answer him.', 'Brothers, come. Which old thing are you treating as if it had not passed? Don’t give it the last word. If the Spirit is pressing you, do not wait for a better feeling. Answer him.'],
        closingPrayer: ['Father, thank you for your Word. Plant this truth in us for the week we actually have. Give us courage to obey and mercy when we fail. Through Jesus Christ. Amen.', 'Lord, we have heard you. Now keep us from leaving this room unchanged. Make us doers of the Word. In Jesus’ name. Amen.'],
        questions: [
          [
            'Which old thing are you treating as if it had not passed?',
            'How should a new creature handle the sin that still knocks?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
          [
            'What name have you been answering to that Christ already replaced?',
            'What would this week look like if the new standing were the one you believed?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
        ],
      },
    es: {
        title: ['Nueva criatura en Cristo', 'El veredicto viejo no es tu nombre'],
        bigIdea: ['Di quién eres en Cristo, desde este versículo, antes de repasar quién fuiste.', 'El mensaje de Pablo es directo: en Cristo, nueva criatura.'],
        openingHook: ['En Cristo, el veredicto viejo no es la última palabra. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.', 'Si alguno está en Cristo, nueva criatura es. Las cosas viejas pasaron. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.'],
        context: ['Pablo explica por qué los creyentes ya no viven para sí. La novedad no es una mejora de personalidad. Es una nueva posición, porque Cristo murió y resucitó, y la persona está en él. Las cosas viejas pasaron. He aquí todas son hechas nuevas. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.', '2 Corintios 5 ata la nueva criatura a la cruz. Murió por todos, para que los que viven ya no vivan para sí. El nombre cambia porque la posición cambió. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.'],
        points: [
          { heading: ['Oye lo que Dios ya dijo', 'Empieza con la Palabra, no con la semana'], thought: ['En Cristo, el veredicto viejo no es la última palabra. Esa línea no es un lema. Es la puerta al texto.', 'Si alguno está en Cristo, nueva criatura es. Las cosas viejas pasaron. Esa línea no es un lema. Es la puerta al texto.'] },
          { heading: ['Mira dónde se asienta el pasaje', 'La historia detrás de la frase'], thought: ['Pablo explica por qué los creyentes ya no viven para sí. Quédate ahí el tiempo suficiente para que el cuarto se calle.', '2 Corintios 5 ata la nueva criatura a la cruz. Quédate ahí el tiempo suficiente para que el cuarto se calle.'] },
          { heading: ['Da el siguiente paso de obediencia', 'Sal con un sí claro'], thought: ['Di quién eres en Cristo, desde este versículo, antes de repasar quién fuiste. Luego vive la semana como esa persona.', 'El mensaje de Pablo es directo: en Cristo, nueva criatura. El veredicto viejo no es tu nombre.'] },
        ],
        application: ['Casi todos nos presentamos por el fracaso viejo y luego nos extraña vivir allí. Cuando repaso el nombre viejo. Cuando negocio con un pecado como si Cristo no me hubiera hecho nuevo. El versículo no niega el pasado. Rehúsa dejar que el pasado sea tu nombre. Una nueva criatura todavía se arrepiente. No se muda otra vez al veredicto viejo. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.', 'El golpe de la vida vieja es real. Responderle es una elección. Di quién eres en Cristo antes de repasar quién fuiste. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.'],
        invitation: ['Hermanos, vengan. ¿A qué nombre viejo sigues respondiendo? El fracaso. La etiqueta que alguien te puso. El pecado que empezaste a llamar tu personalidad. Quizás un veredicto que sigues leyendo después de que Cristo lo rompió. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.', 'Hermanos, vengan. ¿Qué cosa vieja estás tratando como si no hubiera pasado? No le des la última palabra. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.'],
        closingPrayer: ['Padre, gracias por tu Palabra. Siembra esta verdad en nosotros para la semana que de verdad tenemos. Danos valor para obedecer y misericordia cuando fallemos. Por Jesucristo. Amén.', 'Señor, te hemos oído. Ahora no dejes que salgamos de este cuarto sin cambio. Haznos hacedores de la Palabra. En el nombre de Jesús. Amén.'],
        questions: [
          [
            '¿Qué cosa vieja estás tratando como si no hubiera pasado?',
            '¿Cómo debe manejar una nueva criatura el pecado que todavía llama?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
          [
            '¿A qué nombre has estado respondiendo que Cristo ya reemplazó?',
            '¿Cómo se vería esta semana si creyeras la posición nueva?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
        ],
      },
    pt: {
        title: ['Nova criatura em Cristo', 'O veredicto antigo não é o seu nome'],
        bigIdea: ['Diga quem você é em Cristo, a partir deste versículo, antes de repassar quem foi.', 'A mensagem de Paulo é direta: em Cristo, nova criatura.'],
        openingHook: ['Em Cristo, o veredito velho não é a última palavra. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.', 'Se alguém está em Cristo, nova criatura é. As coisas velhas já passaram. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.'],
        context: ['Paulo explica por que os crentes já não vivem para si. A novidade não é um upgrade de personalidade. É uma nova posição, porque Cristo morreu e ressuscitou, e a pessoa está nele. As coisas velhas já passaram. Eis que tudo se fez novo. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.', '2 Coríntios 5 ata a nova criatura à cruz. Ele morreu por todos, para que os que vivem não vivam mais para si. O nome muda porque a posição mudou. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.'],
        points: [
          { heading: ['Ouça o que Deus já disse', 'Comece pela Palavra, não pela semana'], thought: ['Em Cristo, o veredito velho não é a última palavra. Essa linha não é um lema. É a porta para o texto.', 'Se alguém está em Cristo, nova criatura é. As coisas velhas já passaram. Essa linha não é um lema. É a porta para o texto.'] },
          { heading: ['Veja onde a passagem se assenta', 'A história por trás da frase'], thought: ['Paulo explica por que os crentes já não vivem para si. Fique ali tempo bastante para a sala se aquietar.', '2 Coríntios 5 ata a nova criatura à cruz. Fique ali tempo bastante para a sala se aquietar.'] },
          { heading: ['Dê o próximo passo de obediência', 'Saia com um sim claro'], thought: ['Diga quem você é em Cristo, a partir deste versículo, antes de repassar quem foi. Depois viva a semana como essa pessoa.', 'A mensagem de Paulo é direta: em Cristo, nova criatura. O veredito velho não é o seu nome.'] },
        ],
        application: ['Quase todos nos apresentamos pelo fracasso velho e depois estranhamos viver ali. Quando eu repasso o nome velho. Quando negocio com um pecado como se Cristo não me tivesse feito novo. O versículo não nega o passado. Recusa deixar que o passado seja o seu nome. Uma nova criatura ainda se arrepende. Não se muda de volta para o veredito velho. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.', 'A batida da vida velha é real. Atender a ela é uma escolha. Diga quem você é em Cristo antes de repassar quem você foi. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.'],
        invitation: ['Irmãos, venham. A que nome velho você ainda atende? O fracasso. O rótulo que alguém lhe pôs. O pecado que você começou a chamar de personalidade. Talvez um veredito que você continua lendo depois que Cristo o rasgou. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.', 'Irmãos, venham. Que coisa velha você trata como se não tivesse passado? Não lhe dê a última palavra. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.'],
        closingPrayer: ['Pai, obrigado pela tua Palavra. Planta esta verdade em nós para a semana que de fato temos. Dá-nos coragem para obedecer e misericórdia quando falharmos. Por Jesus Cristo. Amém.', 'Senhor, nós te ouvimos. Agora não nos deixes sair desta sala sem mudança. Faz-nos praticantes da Palavra. Em nome de Jesus. Amém.'],
        questions: [
          [
            'Que coisa velha você trata como se não tivesse passado?',
            'Como uma nova criatura deve lidar com o pecado que ainda bate?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
          [
            'A que nome você tem atendido que Cristo já substituiu?',
            'Como esta semana seria se você cresse na posição nova?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
        ],
      },
  },
  'grief': {
    en: {
        title: ['Near to the Brokenhearted', 'He Does Not Wait at a Distance'],
        bigIdea: ['If it is you, come near.', 'David’s message is direct: the Lord is nigh unto the brokenhearted.'],
        openingHook: ['The Lord is near the brokenhearted. He does not wait at a distance. This is not a lecture for somebody else. It is for the week you actually have.', 'Grief is not a failure of faith. Hiding it from God is. This is not a lecture for somebody else. It is for the week you actually have.'],
        context: ['David sings of deliverance and then of the crushed. The Lord is nigh unto them that are of a broken heart, and saveth such as be of a contrite spirit. Nearness is the promise. He does not tell the grieving to hurry up and look fine. That is why this passage still belongs in a class that wants more than a slogan.', 'Psalm 34 is a song from a man who has been in trouble. The broken heart is not sent to the back of the line. God comes near. He saves the contrite. That is why this passage still belongs in a class that wants more than a slogan.'],
        points: [
          { heading: ['Hear what God already said', 'Start with the Word, not the week'], thought: ['The Lord is near the brokenhearted. He does not wait at a distance. That line is not a slogan. It is the doorway into the text.', 'Grief is not a failure of faith. Hiding it from God is. That line is not a slogan. It is the doorway into the text.'] },
          { heading: ['See where the passage sits', 'The story behind the sentence'], thought: ['David sings of deliverance and then of the crushed. Stay there long enough for the room to quiet down.', 'Psalm 34 is a song from a man who has been in trouble. Stay there long enough for the room to quiet down.'] },
          { heading: ['Take the next obedient step', 'Leave with one clear yes'], thought: ['If it is you, come near. He is already there. If it is someone else, go near them this week and do not fix them with a speech.', 'David’s message is direct: the Lord is nigh unto the brokenhearted. Don’t stand at a distance from a person he has drawn close.'] },
        ],
        application: ['Most of us rush a person past a grave. When we don’t know what to say. When the tears make the room uncomfortable. When we quote a verse to end the ache. The church should sit near, because her Lord already does. If the broken heart is yours, come near. He is already there. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.', 'A speech is not nearness. Presence is. Don’t fix them. Sit with them. And don’t carry the loss as if God were far. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.'],
        invitation: ['Brothers, come. Who is brokenhearted in this room, or in your house, that you have kept at arm’s length? A widow. A man who just buried someone. Maybe you. If the Spirit is pressing you, do not wait for a better feeling. Answer him.', 'Brothers, come. What loss have you been carrying as if God were far? Bring it here. He is nigh. If the Spirit is pressing you, do not wait for a better feeling. Answer him.'],
        closingPrayer: ['Father, thank you for your Word. Plant this truth in us for the week we actually have. Give us courage to obey and mercy when we fail. Through Jesus Christ. Amen.', 'Lord, we have heard you. Now keep us from leaving this room unchanged. Make us doers of the Word. In Jesus’ name. Amen.'],
        questions: [
          [
            'What loss have you been carrying as if God were far?',
            'How can this class be near someone who is crushed, without pretending the pain is small?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
          [
            'Who needs your presence this week more than your explanation?',
            'What have you been hiding from God because grief felt like weak faith?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
        ],
      },
    es: {
        title: ['Cerca de los quebrantados', 'Él no espera a distancia'],
        bigIdea: ['Si eres tú, acércate.', 'El mensaje de David es directo: cercano está Jehová a los quebrantados de corazón.'],
        openingHook: ['El Señor está cerca de los quebrantados. No espera a distancia. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.', 'El luto no es una falta de fe. Esconderlo de Dios sí lo es. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.'],
        context: ['David canta la liberación y luego los quebrantados. Cercano está Jehová a los quebrantados de corazón, y salva a los contritos de espíritu. La cercanía es la promesa. No le dice al que llora que se apure y se vea bien. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.', 'El Salmo 34 es un canto de un hombre que ha estado en apuros. Al corazón quebrantado no lo mandan al final de la fila. Dios se acerca. Salva al contrito. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.'],
        points: [
          { heading: ['Oye lo que Dios ya dijo', 'Empieza con la Palabra, no con la semana'], thought: ['El Señor está cerca de los quebrantados. No espera a distancia. Esa línea no es un lema. Es la puerta al texto.', 'El luto no es una falta de fe. Esconderlo de Dios sí lo es. Esa línea no es un lema. Es la puerta al texto.'] },
          { heading: ['Mira dónde se asienta el pasaje', 'La historia detrás de la frase'], thought: ['David canta la liberación y luego los quebrantados. Quédate ahí el tiempo suficiente para que el cuarto se calle.', 'El Salmo 34 es un canto de un hombre que ha estado en apuros. Quédate ahí el tiempo suficiente para que el cuarto se calle.'] },
          { heading: ['Da el siguiente paso de obediencia', 'Sal con un sí claro'], thought: ['Si eres tú, acércate. Él ya está allí. Si es otro, acércate esta semana y no lo arregles con un discurso.', 'El mensaje de David es directo: cercano está Jehová a los quebrantados de corazón. No te quedes a distancia de una persona a la que él se acercó.'] },
        ],
        application: ['Casi todos empujamos a una persona más allá de una tumba. Cuando no sabemos qué decir. Cuando las lágrimas incomodan el cuarto. Cuando citamos un versículo para acabar el dolor. La iglesia debe sentarse cerca, porque su Señor ya lo hace. Si el corazón quebrantado es el tuyo, acércate. Él ya está allí. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.', 'Un discurso no es cercanía. La presencia sí. No los arregles. Siéntate con ellos. Y no cargues la pérdida como si Dios estuviera lejos. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.'],
        invitation: ['Hermanos, vengan. ¿Quién está quebrantado en este cuarto, o en tu casa, y lo has dejado a un brazo de distancia? Una viuda. Un hombre que acaba de enterrar a alguien. Quizás tú. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.', 'Hermanos, vengan. ¿Qué pérdida has cargado como si Dios estuviera lejos? Tráela aquí. Él está cercano. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.'],
        closingPrayer: ['Padre, gracias por tu Palabra. Siembra esta verdad en nosotros para la semana que de verdad tenemos. Danos valor para obedecer y misericordia cuando fallemos. Por Jesucristo. Amén.', 'Señor, te hemos oído. Ahora no dejes que salgamos de este cuarto sin cambio. Haznos hacedores de la Palabra. En el nombre de Jesús. Amén.'],
        questions: [
          [
            '¿Qué pérdida has cargado como si Dios estuviera lejos?',
            '¿Cómo puede esta clase estar cerca de alguien quebrantado, sin fingir que el dolor es pequeño?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
          [
            '¿Quién necesita tu presencia esta semana más que tu explicación?',
            '¿Qué has estado escondiendo de Dios porque el luto te parecía poca fe?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
        ],
      },
    pt: {
        title: ['Perto dos quebrantados', 'Ele não espera à distância'],
        bigIdea: ['Se é você, chegue perto.', 'A mensagem de Davi é direta: perto está o Senhor dos quebrantados de coração.'],
        openingHook: ['O Senhor está perto dos quebrantados. Ele não espera de longe. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.', 'O luto não é falta de fé. Escondê-lo de Deus é. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.'],
        context: ['Davi canta o livramento e depois os quebrantados. Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito. A proximidade é a promessa. Ele não manda o enlutado se apressar e parecer bem. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.', 'O Salmo 34 é um cântico de um homem que esteve em aperto. O coração quebrantado não é mandado para o fim da fila. Deus chega perto. Salva o contrito. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.'],
        points: [
          { heading: ['Ouça o que Deus já disse', 'Comece pela Palavra, não pela semana'], thought: ['O Senhor está perto dos quebrantados. Ele não espera de longe. Essa linha não é um lema. É a porta para o texto.', 'O luto não é falta de fé. Escondê-lo de Deus é. Essa linha não é um lema. É a porta para o texto.'] },
          { heading: ['Veja onde a passagem se assenta', 'A história por trás da frase'], thought: ['Davi canta o livramento e depois os quebrantados. Fique ali tempo bastante para a sala se aquietar.', 'O Salmo 34 é um cântico de um homem que esteve em aperto. Fique ali tempo bastante para a sala se aquietar.'] },
          { heading: ['Dê o próximo passo de obediência', 'Saia com um sim claro'], thought: ['Se é você, chegue perto. Ele já está ali. Se é outra pessoa, chegue perto nesta semana e não a conserte com um discurso.', 'A mensagem de Davi é direta: perto está o Senhor dos quebrantados de coração. Não fique longe de uma pessoa de quem ele se aproximou.'] },
        ],
        application: ['Quase todos empurramos uma pessoa para além do túmulo. Quando não sabemos o que dizer. Quando as lágrimas incomodam a sala. Quando citamos um versículo para acabar a dor. A igreja deve sentar-se perto, porque o seu Senhor já faz isso. Se o coração quebrantado é o seu, chegue perto. Ele já está ali. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.', 'Um discurso não é proximidade. A presença é. Não os conserte. Sente-se com eles. E não carregue a perda como se Deus estivesse longe. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.'],
        invitation: ['Irmãos, venham. Quem está quebrantado nesta sala, ou na sua casa, e você deixou à distância de um braço? Uma viúva. Um homem que acabou de enterrar alguém. Talvez você. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.', 'Irmãos, venham. Que perda você tem carregado como se Deus estivesse longe? Traga para cá. Ele está perto. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.'],
        closingPrayer: ['Pai, obrigado pela tua Palavra. Planta esta verdade em nós para a semana que de fato temos. Dá-nos coragem para obedecer e misericórdia quando falharmos. Por Jesus Cristo. Amém.', 'Senhor, nós te ouvimos. Agora não nos deixes sair desta sala sem mudança. Faz-nos praticantes da Palavra. Em nome de Jesus. Amém.'],
        questions: [
          [
            'Que perda você tem carregado como se Deus estivesse longe?',
            'Como esta classe pode estar perto de alguém quebrantado, sem fingir que a dor é pequena?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
          [
            'Quem precisa da sua presença nesta semana mais do que da sua explicação?',
            'O que você tem escondido de Deus porque o luto parecia pouca fé?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
        ],
      },
  },
  'unity': {
    en: {
        title: ['Keep the Unity of the Spirit', 'Guard What the Spirit Already Made'],
        bigIdea: ['If it must be said, say it to the person.', 'Paul’s message is direct: endeavor to keep the unity of the Spirit.'],
        openingHook: ['Unity is something you keep, not something you feel into existence. This is not a lecture for somebody else. It is for the week you actually have.', 'The Spirit already made you one. Your work is to guard it. This is not a lecture for somebody else. It is for the week you actually have.'],
        context: ['Paul begs the Ephesians to walk worthy of their calling, with lowliness and longsuffering. Then he says endeavor to keep the unity of the Spirit in the bond of peace. They don’t invent the unity. They guard what the Spirit has already made. That is why this passage still belongs in a class that wants more than a slogan.', 'A bond of peace is not a mood that visits when everyone agrees. Endeavor means effort. Patience when a brother is slow. Silence when a story is not yours to carry. That is why this passage still belongs in a class that wants more than a slogan.'],
        points: [
          { heading: ['Hear what God already said', 'Start with the Word, not the week'], thought: ['Unity is something you keep, not something you feel into existence. That line is not a slogan. It is the doorway into the text.', 'The Spirit already made you one. Your work is to guard it. That line is not a slogan. It is the doorway into the text.'] },
          { heading: ['See where the passage sits', 'The story behind the sentence'], thought: ['Paul begs the Ephesians to walk worthy of their calling, with lowliness and longsuffering. Stay there long enough for the room to quiet down.', 'A bond of peace is not a mood that visits when everyone agrees. Stay there long enough for the room to quiet down.'] },
          { heading: ['Take the next obedient step', 'Leave with one clear yes'], thought: ['If it must be said, say it to the person. Keep what the Spirit has already made.', 'Paul’s message is direct: endeavor to keep the unity of the Spirit. Don’t wait to feel it. Guard it.'] },
        ],
        application: ['Most division starts as a sentence we enjoy. When the story is good. When we tell it about a back instead of to a face. When we watch the split like spectators. We loosen the bond and call it honesty. Paul says endeavor. That is work. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.', 'Truth spoken to a face can keep the peace. The same truth carried around the room breaks it. Keep what the Spirit already made. Take it deeper: do not leave with the same quiet bargain you walked in with. Let the Word rearrange what you call enough, safe, and later.'],
        invitation: ['Brothers, come. What sentence have you repeated that loosens the bond? A joke. A suspicion. A story that wasn’t yours. Maybe a silence while others tore a brother down. If the Spirit is pressing you, do not wait for a better feeling. Answer him.', 'Brothers, come. Where have you been a spectator of division instead of a keeper of peace? Stop carrying it. If the Spirit is pressing you, do not wait for a better feeling. Answer him.'],
        closingPrayer: ['Father, thank you for your Word. Plant this truth in us for the week we actually have. Give us courage to obey and mercy when we fail. Through Jesus Christ. Amen.', 'Lord, we have heard you. Now keep us from leaving this room unchanged. Make us doers of the Word. In Jesus’ name. Amen.'],
        questions: [
          [
            'Where have you been a spectator of division instead of a keeper of peace?',
            'What would endeavor look like with the brother who irritates you?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
          [
            'What story are you still carrying that is not yours to carry?',
            'Who needs the truth said to their face instead of about their back?',
            'What would change this week if you believed this passage was for your actual life, not only for the class hour?',
            'Who needs you to live this out where they can see it — and what is one concrete step?',
          ],
        ],
      },
    es: {
        title: ['Guardad la unidad del Espíritu', 'Custodia lo que el Espíritu ya hizo'],
        bigIdea: ['Si hay que decirla, díganla a la persona.', 'El mensaje de Pablo es directo: solícitos en guardar la unidad del Espíritu.'],
        openingHook: ['La unidad se guarda. No se siente hasta que aparezca. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.', 'El Espíritu ya los hizo uno. El trabajo de ustedes es guardarlo. Esto no es una conferencia para otra persona. Es para la semana que de verdad tienes.'],
        context: ['Pablo ruega a los efesios que anden como es digno de su vocación, con humildad y mansedumbre. Luego dice que solícitos guarden la unidad del Espíritu en el vínculo de la paz. No inventan la unidad. Guardan lo que el Espíritu ya hizo. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.', 'Un vínculo de paz no es un ánimo que visita cuando todos están de acuerdo. Solicitud significa esfuerzo. Paciencia cuando un hermano es lento. Silencio cuando una historia no es tuya para cargar. Por eso este pasaje todavía pertenece a una clase que quiere más que un lema.'],
        points: [
          { heading: ['Oye lo que Dios ya dijo', 'Empieza con la Palabra, no con la semana'], thought: ['La unidad se guarda. No se siente hasta que aparezca. Esa línea no es un lema. Es la puerta al texto.', 'El Espíritu ya los hizo uno. El trabajo de ustedes es guardarlo. Esa línea no es un lema. Es la puerta al texto.'] },
          { heading: ['Mira dónde se asienta el pasaje', 'La historia detrás de la frase'], thought: ['Pablo ruega a los efesios que anden como es digno de su vocación, con humildad y mansedumbre. Quédate ahí el tiempo suficiente para que el cuarto se calle.', 'Un vínculo de paz no es un ánimo que visita cuando todos están de acuerdo. Quédate ahí el tiempo suficiente para que el cuarto se calle.'] },
          { heading: ['Da el siguiente paso de obediencia', 'Sal con un sí claro'], thought: ['Si hay que decirla, díganla a la persona. Guarden lo que el Espíritu ya hizo.', 'El mensaje de Pablo es directo: solícitos en guardar la unidad del Espíritu. No esperes sentirla. Guárdala.'] },
        ],
        application: ['Casi toda división empieza como una frase que nos gusta. Cuando el chisme está bueno. Cuando lo decimos a la espalda y no a la cara. Cuando miramos la ruptura como espectadores. Aflojamos el vínculo y lo llamamos honestidad. Pablo dice que seamos solícitos. Eso es trabajo. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.', 'La verdad dicha a la cara puede guardar la paz. La misma verdad paseada por el cuarto la rompe. Guarda lo que el Espíritu ya hizo. Llévalo más hondo: no salgas con el mismo trato silencioso con el que entraste. Deja que la Palabra reordene lo que llamas suficiente, seguro y después.'],
        invitation: ['Hermanos, vengan. ¿Qué frase has repetido que afloja el vínculo? Un chiste. Una sospecha. Una historia que no era tuya. Quizás un silencio mientras otros bajaban a un hermano. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.', 'Hermanos, vengan. ¿Dónde has sido espectador de la división en vez de guardar la paz? Deja de cargarla. Si el Espíritu te está apretando, no esperes un mejor sentimiento. Respóndele.'],
        closingPrayer: ['Padre, gracias por tu Palabra. Siembra esta verdad en nosotros para la semana que de verdad tenemos. Danos valor para obedecer y misericordia cuando fallemos. Por Jesucristo. Amén.', 'Señor, te hemos oído. Ahora no dejes que salgamos de este cuarto sin cambio. Haznos hacedores de la Palabra. En el nombre de Jesús. Amén.'],
        questions: [
          [
            '¿Dónde has sido espectador de la división en vez de guardar la paz?',
            '¿Cómo se vería procurar la unidad con el hermano que te irrita?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
          [
            '¿Qué historia sigues cargando que no es tuya para cargar?',
            '¿A quién hay que decirle la verdad a la cara y no a la espalda?',
            '¿Qué cambiaría esta semana si creyeras que este pasaje es para tu vida real, no solo para la hora de clase?',
            '¿Quién necesita verte vivir esto — y cuál es un paso concreto?',
          ],
        ],
      },
    pt: {
        title: ['Guardai a unidade do Espírito', 'Guarde o que o Espírito já fez'],
        bigIdea: ['Se precisa ser dita, digam à pessoa.', 'A mensagem de Paulo é direta: procurai guardar a unidade do Espírito.'],
        openingHook: ['A unidade se guarda. Não se espera sentir até ela aparecer. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.', 'O Espírito já os fez um. O trabalho de vocês é guardá-la. Isto não é uma palestra para outra pessoa. É para a semana que você de fato tem.'],
        context: ['Paulo roga aos efésios que andem como é digno da vocação, com humildade e mansidão. Depois diz que procureis guardar a unidade do Espírito no vínculo da paz. Eles não inventam a unidade. Guardam o que o Espírito já fez. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.', 'Um vínculo de paz não é um humor que visita quando todos concordam. Procurar significa esforço. Paciência quando um irmão é lento. Silêncio quando uma história não é sua para carregar. Por isso esta passagem ainda pertence a uma classe que quer mais do que um lema.'],
        points: [
          { heading: ['Ouça o que Deus já disse', 'Comece pela Palavra, não pela semana'], thought: ['A unidade se guarda. Não se espera sentir até ela aparecer. Essa linha não é um lema. É a porta para o texto.', 'O Espírito já os fez um. O trabalho de vocês é guardá-la. Essa linha não é um lema. É a porta para o texto.'] },
          { heading: ['Veja onde a passagem se assenta', 'A história por trás da frase'], thought: ['Paulo roga aos efésios que andem como é digno da vocação, com humildade e mansidão. Fique ali tempo bastante para a sala se aquietar.', 'Um vínculo de paz não é um humor que visita quando todos concordam. Fique ali tempo bastante para a sala se aquietar.'] },
          { heading: ['Dê o próximo passo de obediência', 'Saia com um sim claro'], thought: ['Se precisa ser dita, digam à pessoa. Guardem o que o Espírito já fez.', 'A mensagem de Paulo é direta: procurai guardar a unidade do Espírito. Não espere sentir. Guarde.'] },
        ],
        application: ['Quase toda divisão começa como uma frase de que gostamos. Quando a fofoca está boa. Quando falamos pelas costas e não à face. Quando olhamos a ruptura como espectadores. Afrouxamos o vínculo e chamamos de honestidade. Paulo diz para procurar. Isso é trabalho. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.', 'A verdade dita à face pode guardar a paz. A mesma verdade passeada pela sala a quebra. Guardem o que o Espírito já fez. Leve mais fundo: não saia com o mesmo acordo quieto com que entrou. Deixe a Palavra reordenar o que você chama de bastante, seguro e depois.'],
        invitation: ['Irmãos, venham. Que frase você tem repetido que afrouxa o vínculo? Uma piada. Uma suspeita. Uma história que não era sua. Talvez um silêncio enquanto outros derrubavam um irmão. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.', 'Irmãos, venham. Onde você tem sido espectador da divisão em vez de guardar a paz? Pare de carregá-la. Se o Espírito está apertando você, não espere um sentimento melhor. Responda a ele.'],
        closingPrayer: ['Pai, obrigado pela tua Palavra. Planta esta verdade em nós para a semana que de fato temos. Dá-nos coragem para obedecer e misericórdia quando falharmos. Por Jesus Cristo. Amém.', 'Senhor, nós te ouvimos. Agora não nos deixes sair desta sala sem mudança. Faz-nos praticantes da Palavra. Em nome de Jesus. Amém.'],
        questions: [
          [
            'Onde você tem sido espectador da divisão em vez de guardar a paz?',
            'Como seria procurar a unidade com o irmão que irrita você?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
          [
            'Que história você ainda carrega que não é sua para carregar?',
            'A quem a verdade precisa ser dita à face e não pelas costas?',
            'O que mudaria nesta semana se você cresse que esta passagem é para a sua vida real, não só para a hora da classe?',
            'Quem precisa ver você viver isto — e qual é um passo concreto?',
          ],
        ],
      },
  },
}
