import type { Language } from '../i18n/messages'
import type { VerseRef } from './types'

export type GospelPack = {
  id: string
  keywords: readonly string[]
  refs: readonly VerseRef[]
  note: Record<Language, string>
}

function verses(...rows: readonly (readonly [string, number, number])[]): VerseRef[] {
  return rows.map(([bookId, chapter, verse]) => ({ bookId, chapter, verse }))
}

function pack(
  id: string,
  keywords: readonly string[],
  refs: readonly VerseRef[],
  en: string,
  es: string,
  pt: string,
): GospelPack {
  return { id, keywords, refs, note: { en, es, pt } }
}

/**
 * Curated themes. The verse words are loaded later from the Bible the reader is using.
 * Notes stay short, name what the text says, and leave the chapter and the pastor in place.
 */
export const PACKS: readonly GospelPack[] = [
  pack(
    'gospel',
    [
      'gospel',
      'good news',
      'evangelio',
      'buenas nuevas',
      'evangelho',
      'boas novas',
      'salvation',
      'saved',
      'salvo',
      'salvacion',
      'salvacao',
      'how can i be saved',
      'how to be saved',
      'what must i do to be saved',
      'como ser salvo',
      'como puedo ser salvo',
      'que debo hacer para ser salvo',
      'como posso ser salvo',
      'o que devo fazer para ser salvo',
      'plan of salvation',
      'plan de salvacion',
      'plano de salvacao',
      'born again',
      'nacer de nuevo',
      'nacido de nuevo',
      'nascer de novo',
      'novo nascimento',
    ],
    verses(['jhn', 3, 16], ['rom', 3, 23], ['rom', 5, 8], ['rom', 10, 9]),
    'The gospel is God’s good news. Scripture says all have sinned, that Christ died for sinners and rose, and that whoever believes in him is saved. Read these verses in their chapters.',
    'El evangelio es las buenas nuevas de Dios. La Escritura dice que todos pecaron, que Cristo murió por los pecadores y resucitó, y que todo el que cree en él es salvo. Léelos en sus capítulos.',
    'O evangelho é as boas novas de Deus. A Escritura diz que todos pecaram, que Cristo morreu pelos pecadores e ressuscitou, e que todo aquele que crê nele é salvo. Leia estes versículos nos seus capítulos.',
  ),
  pack(
    'jesus',
    [
      'jesus',
      'jesucristo',
      'jesus cristo',
      'christ',
      'cristo',
      'messiah',
      'mesias',
      'who is jesus',
      'quien es jesus',
      'quem e jesus',
      'is jesus god',
      'jesus es dios',
      'jesus e deus',
    ],
    verses(['jhn', 1, 1], ['jhn', 14, 6], ['col', 1, 15], ['heb', 1, 3]),
    'Scripture calls Jesus the Word who was God, the way to the Father, and the image of the invisible God. These verses are the texts. They are not a new life of Jesus written for this chat.',
    'La Escritura llama a Jesús el Verbo que era Dios, el camino al Padre, y la imagen del Dios invisible. Estos versículos son los textos. No son una vida nueva de Jesús escrita para este chat.',
    'A Escritura chama Jesus de Verbo que era Deus, o caminho para o Pai, e a imagem do Deus invisível. Estes versículos são os textos. Não são uma nova vida de Jesus escrita para este chat.',
  ),
  pack(
    'sin',
    ['sin', 'sins', 'sinner', 'pecado', 'pecados', 'pecador'],
    verses(['rom', 3, 23], ['isa', 53, 6], ['1jn', 1, 8], ['rom', 6, 23]),
    'Scripture says every person has sinned, and that the wages of sin is death. It also says the gift of God is eternal life in Christ Jesus. The honest reading starts with the debt, and it does not stop there.',
    'La Escritura dice que toda persona pecó, y que la paga del pecado es muerte. También dice que la dádiva de Dios es vida eterna en Cristo Jesús. La lectura honesta empieza por la deuda, y no se queda ahí.',
    'A Escritura diz que toda pessoa pecou, e que o salário do pecado é a morte. Também diz que o dom de Deus é a vida eterna em Cristo Jesus. A leitura honesta começa pela dívida, e não para aí.',
  ),
  pack(
    'grace',
    ['grace', 'gracia', 'graca', 'mercy', 'misericordia'],
    verses(['eph', 2, 8], ['tit', 2, 11], ['rom', 5, 8], ['2co', 12, 9]),
    'Scripture says salvation is by grace through faith, not a wage we earn. Grace teaches us to refuse sin, and it is enough where we are weak. Read the chapters before you turn the word into a slogan.',
    'La Escritura dice que la salvación es por gracia mediante la fe, no un salario que ganamos. La gracia nos enseña a rechazar el pecado, y basta donde somos débiles. Lee los capítulos antes de volver la palabra un lema.',
    'A Escritura diz que a salvação é pela graça, por meio da fé, não um salário que ganhamos. A graça nos ensina a recusar o pecado, e basta onde somos fracos. Leia os capítulos antes de tornar a palavra um lema.',
  ),
  pack(
    'faith',
    ['faith', 'belief', 'believe', 'fe', 'creer', 'crer', 'creencia'],
    verses(['heb', 11, 1], ['eph', 2, 8], ['rom', 10, 17], ['gal', 2, 20]),
    'Scripture says faith is the substance of things hoped for, and that it comes by hearing the word of Christ. It is trust in him, not a mood we produce. A pastor can help you hear the chapter, not only the sentence.',
    'La Escritura dice que la fe es la certeza de lo que se espera, y que viene por el oír la palabra de Cristo. Es confianza en él, no un ánimo que fabricamos. Un pastor puede ayudarte a oír el capítulo, no solo la frase.',
    'A Escritura diz que a fé é a certeza das coisas que se esperam, e que vem pelo ouvir a palavra de Cristo. É confiança nele, não um ânimo que fabricamos. Um pastor pode ajudar você a ouvir o capítulo, não só a frase.',
  ),
  pack(
    'forgiveness',
    ['forgiveness', 'forgive', 'forgiven', 'pardon', 'perdon', 'perdonar', 'perdao', 'perdoar'],
    verses(['1jn', 1, 9], ['eph', 4, 32], ['col', 3, 13], ['psa', 103, 12]),
    'Scripture says that if we confess our sins, God is faithful to forgive, and that he removes our transgressions as far as east is from west. It also tells the forgiven to forgive. Read both sides in the chapter.',
    'La Escritura dice que si confesamos nuestros pecados, Dios es fiel para perdonar, y que aparta nuestras rebeliones tan lejos como el oriente del occidente. También pide que el perdonado perdone. Lee las dos partes en el capítulo.',
    'A Escritura diz que, se confessarmos os nossos pecados, Deus é fiel para perdoar, e que lança as nossas transgressões para longe de nós. Também pede que o perdoado perdoe. Leia os dois lados no capítulo.',
  ),
  pack(
    'repentance',
    ['repentance', 'repent', 'arrepentimiento', 'arrepentirse', 'arrepentirme', 'arrependimento', 'arrepender'],
    verses(['act', 3, 19], ['luk', 13, 3], ['2co', 7, 10], ['1jn', 1, 9]),
    'Scripture calls people to repent and turn to God, so that sins may be blotted out. Godly sorrow leads to repentance. It is a turning, not a performance, and the chapter is the place to see what the turn looks like.',
    'La Escritura llama a arrepentirse y convertirse a Dios, para que los pecados sean borrados. La tristeza que es según Dios produce arrepentimiento. Es un volverse, no una actuación, y el capítulo muestra cómo es ese giro.',
    'A Escritura chama as pessoas a se arrepender e se converter a Deus, para que os pecados sejam apagados. A tristeza segundo Deus produz arrependimento. É uma volta, não uma encenação, e o capítulo mostra como é essa volta.',
  ),
  pack(
    'love',
    ['love', 'loved', 'amor', 'ama', 'god is love', 'dios es amor', 'deus e amor'],
    verses(['1jn', 4, 8], ['jhn', 3, 16], ['rom', 5, 8], ['1co', 13, 4]),
    'Scripture says God is love, and that he showed it by giving his Son while we were still sinners. Love is also patient and kind in the church. These verses belong together. One of them alone is not the whole teaching.',
    'La Escritura dice que Dios es amor, y que lo mostró al dar a su Hijo cuando aún éramos pecadores. El amor también es paciente y benigno en la iglesia. Estos versículos van juntos. Uno solo no es toda la enseñanza.',
    'A Escritura diz que Deus é amor, e que o mostrou ao dar o seu Filho quando ainda éramos pecadores. O amor também é paciente e benigno na igreja. Estes versículos andam juntos. Um só não é todo o ensino.',
  ),
  pack(
    'prayer',
    [
      'prayer',
      'pray',
      'praying',
      'oracion',
      'orar',
      'orando',
      'oracao',
      'how should i pray',
      'how to pray',
      'como debo orar',
      'como orar',
      'como devo orar',
    ],
    verses(['mat', 6, 9], ['php', 4, 6], ['1th', 5, 17], ['mat', 7, 7]),
    'Scripture teaches us to pray to the Father, to bring requests with thanksgiving instead of carrying worry alone, and to keep praying. The Lord’s Prayer is a pattern, not a spell. Read Matthew 6 in place.',
    'La Escritura enseña a orar al Padre, a presentar peticiones con acción de gracias en lugar de cargar la ansiedad solos, y a seguir orando. El Padrenuestro es un modelo, no un conjuro. Lee Mateo 6 en su lugar.',
    'A Escritura ensina a orar ao Pai, a apresentar pedidos com ações de graças em vez de carregar a ansiedade sozinhos, e a continuar orando. A oração do Pai-Nosso é um modelo, não uma fórmula mágica. Leia Mateus 6 no seu lugar.',
  ),
  pack(
    'fear',
    [
      'fear',
      'afraid',
      'anxiety',
      'anxious',
      'worry',
      'worried',
      'miedo',
      'temor',
      'ansiedad',
      'ansioso',
      'preocupacion',
      'preocupado',
      'medo',
      'ansiedade',
      'preocupacao',
    ],
    verses(['isa', 41, 10], ['php', 4, 6], ['2ti', 1, 7], ['psa', 56, 3]),
    'Scripture tells the fearful that God is with them, and it invites them to pray instead of staying alone with the worry. It does not call fear a small thing. If the weight is heavy, talk with your pastor and your local church.',
    'La Escritura dice al temeroso que Dios está con él, y lo invita a orar en lugar de quedarse solo con la preocupación. No llama al miedo una cosa pequeña. Si el peso es mucho, habla con tu pastor y con tu iglesia local.',
    'A Escritura diz a quem teme que Deus está com ele, e o convida a orar em vez de ficar sozinho com a preocupação. Ela não chama o medo de coisa pequena. Se o peso for grande, fale com o seu pastor e com a sua igreja local.',
  ),
  pack(
    'hope',
    ['hope', 'esperanza', 'esperanca'],
    verses(['rom', 15, 13], ['1pe', 1, 3], ['lam', 3, 22], ['psa', 42, 11]),
    'Scripture ties hope to the God of hope, to the resurrection of Jesus, and to mercies that are new. The psalm tells the downcast soul to hope in God. It is a word spoken in a hard place, not a promise that the week will be easy.',
    'La Escritura une la esperanza al Dios de la esperanza, a la resurrección de Jesús, y a misericordias que se renuevan. El salmo dice al alma abatida que espere en Dios. Es una palabra dicha en un lugar difícil, no una promesa de que la semana será fácil.',
    'A Escritura liga a esperança ao Deus da esperança, à ressurreição de Jesus, e a misericórdias que se renovam. O salmo diz à alma abatida que espere em Deus. É uma palavra dita num lugar difícil, não uma promessa de que a semana será fácil.',
  ),
  pack(
    'peace',
    ['peace', 'paz'],
    verses(['jhn', 14, 27], ['php', 4, 7], ['isa', 26, 3], ['col', 3, 15]),
    'Scripture says Jesus gives a peace the world does not give, and that the peace of God guards hearts when we pray. Isaiah speaks of a mind stayed on God. Read the verses in the trouble they were spoken into.',
    'La Escritura dice que Jesús da una paz que el mundo no da, y que la paz de Dios guarda el corazón cuando oramos. Isaías habla de un pensamiento firme en Dios. Lee los versículos en la dificultad en que fueron dichos.',
    'A Escritura diz que Jesus dá uma paz que o mundo não dá, e que a paz de Deus guarda o coração quando oramos. Isaías fala de uma mente firme em Deus. Leia os versículos na dificuldade em que foram ditos.',
  ),
  pack(
    'joy',
    ['joy', 'joyful', 'gozo', 'alegria', 'regocijo'],
    verses(['php', 4, 4], ['jhn', 15, 11], ['neh', 8, 10], ['psa', 16, 11]),
    'Scripture tells the church to rejoice in the Lord, and it says the joy of the Lord is strength. Jesus speaks of his joy remaining in his disciples. It is joy in him, not a demand to pretend the day is light.',
    'La Escritura dice a la iglesia que se regocije en el Señor, y que el gozo del Señor es la fortaleza. Jesús habla de su gozo permaneciendo en los discípulos. Es gozo en él, no una orden de fingir que el día es liviano.',
    'A Escritura diz à igreja que se alegre no Senhor, e que a alegria do Senhor é a força. Jesus fala da sua alegria permanecendo nos discípulos. É alegria nele, não uma ordem de fingir que o dia é leve.',
  ),
  pack(
    'suffering',
    [
      'suffering',
      'suffer',
      'trial',
      'trials',
      'affliction',
      'sufrimiento',
      'tribulacion',
      'afliccion',
      'sofrimento',
      'provacao',
      'tribulacao',
      'aflicao',
    ],
    verses(['rom', 8, 28], ['psa', 34, 18], ['jas', 1, 2], ['2co', 4, 17]),
    'Scripture says God works all things for good for those who love him. It does not say the pain is small. The Lord is near to the brokenhearted. If you are in the middle of it, read this with your pastor, not alone in a chat.',
    'La Escritura dice que Dios dispone todas las cosas para bien de los que lo aman. No dice que el dolor sea pequeño. El Señor está cerca de los quebrantados de corazón. Si estás en medio de ello, léelo con tu pastor, no solo en un chat.',
    'A Escritura diz que Deus faz todas as coisas cooperarem para o bem dos que o amam. Ela não diz que a dor seja pequena. O Senhor está perto dos quebrantados de coração. Se você está no meio disso, leia com o seu pastor, não sozinho num chat.',
  ),
  pack(
    'heaven',
    ['heaven', 'cielo', 'ceu', 'paradise', 'paraiso'],
    verses(['jhn', 14, 2], ['rev', 21, 4], ['php', 3, 20], ['2co', 5, 1]),
    'Scripture says Jesus prepares a place for his people, and that in the end God will wipe away tears and death will be no more. Our citizenship is in heaven. These verses are hope. They are not a map of the furniture there.',
    'La Escritura dice que Jesús prepara un lugar para los suyos, y que al final Dios enjugará las lágrimas y la muerte ya no será. Nuestra ciudadanía está en los cielos. Estos versículos son esperanza. No son un mapa de lo que hay allí.',
    'A Escritura diz que Jesus prepara um lugar para os seus, e que no fim Deus enxugará as lágrimas e a morte já não existirá. A nossa cidadania está nos céus. Estes versículos são esperança. Não são um mapa do que há lá.',
  ),
  pack(
    'spirit',
    ['holy spirit', 'holy ghost', 'espiritu santo', 'espirito santo'],
    verses(['jhn', 14, 26], ['act', 1, 8], ['gal', 5, 22], ['rom', 8, 26]),
    'Scripture says the Holy Spirit teaches, gives power to witness, bears fruit, and helps us when we do not know how to pray. These are his works in the text. A pastor can open the chapters with you.',
    'La Escritura dice que el Espíritu Santo enseña, da poder para testificar, produce fruto, y ayuda cuando no sabemos orar. Estas son sus obras en el texto. Un pastor puede abrir los capítulos contigo.',
    'A Escritura diz que o Espírito Santo ensina, dá poder para testemunhar, produz fruto, e ajuda quando não sabemos orar. Estas são as obras dele no texto. Um pastor pode abrir os capítulos com você.',
  ),
  pack(
    'church',
    ['church', 'iglesia', 'igreja', 'fellowship', 'congregacion', 'congregacao', 'asamblea'],
    verses(['heb', 10, 25], ['mat', 18, 20], ['act', 2, 42], ['1co', 12, 27]),
    'Scripture tells believers not to abandon meeting together. The early church continued in the apostles’ teaching, fellowship, the breaking of bread, and prayers. You are part of a body. A local church is the place that body has a name and a pastor.',
    'La Escritura pide a los creyentes que no dejen de congregarse. La iglesia primera perseveraba en la doctrina de los apóstoles, la comunión, el partimiento del pan y las oraciones. Eres parte de un cuerpo. Una iglesia local es el lugar donde ese cuerpo tiene nombre y pastor.',
    'A Escritura pede aos crentes que não deixem de se reunir. A igreja primeira perseverava na doutrina dos apóstolos, na comunhão, no partir do pão e nas orações. Você é parte de um corpo. Uma igreja local é o lugar onde esse corpo tem nome e pastor.',
  ),
  pack(
    'baptism',
    ['baptism', 'baptize', 'baptized', 'bautismo', 'bautizar', 'bautizado', 'batismo', 'batizar', 'batizado'],
    verses(['mat', 28, 19], ['act', 2, 38], ['rom', 6, 4], ['gal', 3, 27]),
    'Scripture commands baptism in the name of the Father, the Son, and the Holy Spirit, and it joins baptism to dying and rising with Christ. Churches practice the details in different ways. Read these verses with your pastor and your local church.',
    'La Escritura manda bautizar en el nombre del Padre, del Hijo y del Espíritu Santo, y une el bautismo al morir y resucitar con Cristo. Las iglesias practican los detalles de maneras distintas. Lee estos versículos con tu pastor y con tu iglesia local.',
    'A Escritura manda batizar em nome do Pai, do Filho e do Espírito Santo, e liga o batismo ao morrer e ressuscitar com Cristo. As igrejas praticam os detalhes de modos diferentes. Leia estes versículos com o seu pastor e com a sua igreja local.',
  ),
  pack(
    'resurrection',
    ['resurrection', 'resurrected', 'rose from the dead', 'resurreccion', 'resucito', 'ressurreicao', 'ressuscitou'],
    verses(['1co', 15, 3], ['1co', 15, 20], ['jhn', 11, 25], ['rom', 8, 11]),
    'Scripture says Christ died for our sins, was buried, and rose the third day, and that he is the firstfruits of those who sleep. Jesus says he is the resurrection and the life. The chapter in 1 Corinthians 15 is the place to keep reading.',
    'La Escritura dice que Cristo murió por nuestros pecados, fue sepultado y resucitó al tercer día, y que él es las primicias de los que durmieron. Jesús dice que él es la resurrección y la vida. El capítulo de 1 Corintios 15 es el lugar para seguir leyendo.',
    'A Escritura diz que Cristo morreu pelos nossos pecados, foi sepultado e ressuscitou ao terceiro dia, e que ele é as primícias dos que dormem. Jesus diz que ele é a ressurreição e a vida. O capítulo de 1 Coríntios 15 é o lugar para continuar lendo.',
  ),
  pack(
    'cross',
    ['cross', 'crucifixion', 'crucified', 'calvary', 'cruz', 'crucificado', 'calvario'],
    verses(['1co', 1, 18], ['1pe', 2, 24], ['gal', 2, 20], ['col', 2, 14]),
    'Scripture calls the word of the cross the power of God. It says Christ bore our sins in his body on the tree, and that the record against us was nailed there. Paul says he is crucified with Christ and Christ lives in him.',
    'La Escritura llama a la palabra de la cruz poder de Dios. Dice que Cristo llevó nuestros pecados en su cuerpo sobre el madero, y que el acta contra nosotros fue clavada allí. Pablo dice que está crucificado con Cristo y que Cristo vive en él.',
    'A Escritura chama a palavra da cruz de poder de Deus. Diz que Cristo levou os nossos pecados no seu corpo sobre o madeiro, e que o escrito contra nós foi pregado ali. Paulo diz que está crucificado com Cristo e que Cristo vive nele.',
  ),
  pack(
    'word',
    [
      'bible',
      'scripture',
      'scriptures',
      'biblia',
      'escritura',
      'escrituras',
      'word of god',
      'palabra de dios',
      'palavra de deus',
    ],
    verses(['2ti', 3, 16], ['psa', 119, 105], ['heb', 4, 12], ['jos', 1, 8]),
    'Scripture says all Scripture is given by inspiration of God and is profitable. The psalm calls the word a lamp. Hebrews says it is living and active. This chat quotes it. It does not replace reading the book.',
    'La Escritura dice que toda la Escritura es inspirada por Dios y útil. El salmo llama a la palabra una lámpara. Hebreos dice que es viva y eficaz. Este chat la cita. No reemplaza la lectura del libro.',
    'A Escritura diz que toda a Escritura é inspirada por Deus e útil. O salmo chama a palavra de lâmpada. Hebreus diz que ela é viva e eficaz. Este chat a cita. Ele não substitui a leitura do livro.',
  ),
  pack(
    'marriage',
    [
      'marriage',
      'marry',
      'wedding',
      'husband',
      'wife',
      'matrimonio',
      'casamiento',
      'esposo',
      'esposa',
      'casamento',
      'marido',
    ],
    verses(['gen', 2, 24], ['mrk', 10, 9], ['eph', 5, 25], ['heb', 13, 4]),
    'Scripture speaks of a man and a woman joined by God, and of a husband loving his wife as Christ loved the church. Marriage is to be held in honor. These are the texts. A pastor can walk through them with you.',
    'La Escritura habla de un hombre y una mujer unidos por Dios, y de un esposo que ama a su esposa como Cristo amó a la iglesia. El matrimonio debe ser honroso. Estos son los textos. Un pastor puede leerlos contigo.',
    'A Escritura fala de um homem e uma mulher unidos por Deus, e de um marido que ama a sua esposa como Cristo amou a igreja. O casamento deve ser honrado. Estes são os textos. Um pastor pode lê-los com você.',
  ),
  pack(
    'anger',
    ['anger', 'angry', 'wrath', 'furious', 'enojo', 'enojado', 'furioso', 'colera', 'raiva', 'irado'],
    verses(['eph', 4, 26], ['jas', 1, 19], ['pro', 15, 1], ['col', 3, 8]),
    'Scripture says to be angry and not sin, and not to let the sun go down on wrath. It also says to be slow to anger, and to put wrath away. A soft answer turns away wrath. The chapter tells you what to do with the heat.',
    'La Escritura dice que se puede airar y no pecar, y que el sol no se ponga sobre el enojo. También dice que seamos tardos para airarnos, y que dejemos la ira. La blanda respuesta quita la ira. El capítulo dice qué hacer con el fuego.',
    'A Escritura diz que é possível irar-se e não pecar, e que o sol não se ponha sobre a ira. Também diz que sejamos tardos para irar, e que deixemos a ira. A resposta branda desvia o furor. O capítulo diz o que fazer com o fogo.',
  ),
  pack(
    'money',
    [
      'money',
      'greed',
      'mammon',
      'riches',
      'dinero',
      'codicia',
      'avaricia',
      'riqueza',
      'dinheiro',
      'cobica',
      'ganancia',
    ],
    verses(['mat', 6, 24], ['1ti', 6, 10], ['heb', 13, 5], ['2co', 9, 7]),
    'Scripture does not call money itself the root of all evil. It warns that the love of money is. You cannot serve God and money. Godliness with contentment is the setting of that warning. Read the paragraph, not only the famous line.',
    'La Escritura no llama al dinero mismo la raíz de todos los males. Advierte que el amor al dinero lo es. No se puede servir a Dios y a las riquezas. La piedad con contentamiento es el lugar de esa advertencia. Lee el párrafo, no solo la frase famosa.',
    'A Escritura não chama o dinheiro em si de raiz de todos os males. Ela adverte que o amor ao dinheiro o é. Ninguém pode servir a Deus e às riquezas. A piedade com contentamento é o lugar dessa advertência. Leia o parágrafo, não só a frase famosa.',
  ),
  pack(
    'doubt',
    ['doubt', 'doubts', 'unbelief', 'duda', 'dudas', 'incredulidad', 'duvida', 'duvidas', 'incredulidade'],
    verses(['mrk', 9, 24], ['jas', 1, 5], ['jhn', 20, 27], ['jud', 1, 22]),
    'Scripture includes a father who says, “I believe; help my unbelief.” James says to ask God for wisdom. Jesus meets Thomas in the doubt and shows him his wounds. Bring the question to the text and to your pastor. Hiding it does not make it smaller.',
    'La Escritura incluye a un padre que dice: «Creo; ayuda mi incredulidad». Santiago dice que pidamos a Dios sabiduría. Jesús encuentra a Tomás en la duda y le muestra las heridas. Lleva la pregunta al texto y a tu pastor. Esconderla no la achica.',
    'A Escritura inclui um pai que diz: «Eu creio; ajuda a minha incredulidade». Tiago diz que peçamos a Deus sabedoria. Jesus encontra Tomé na dúvida e lhe mostra as feridas. Leve a pergunta ao texto e ao seu pastor. Escondê-la não a diminui.',
  ),
  pack(
    'temptation',
    ['temptation', 'tempt', 'tempted', 'tentacion', 'tentar', 'tentacao', 'tentado'],
    verses(['1co', 10, 13], ['heb', 4, 15], ['jas', 4, 7], ['mat', 6, 13]),
    'Scripture says no temptation has overtaken you except what is common, and that God makes a way of escape. Christ was tempted and did not sin, so he can sympathize. Submit to God and resist the devil. The prayer Jesus taught asks not to be led into temptation.',
    'La Escritura dice que ninguna tentación os ha tomado sino la humana, y que Dios da la salida. Cristo fue tentado y no pecó, así que puede compadecerse. Someteos a Dios y resistid al diablo. La oración que Jesús enseñó pide no entrar en tentación.',
    'A Escritura diz que nenhuma tentação vos sobreveio que não fosse humana, e que Deus dá o escape. Cristo foi tentado e não pecou, por isso pode compadecer-se. Sujeitai-vos a Deus e resisti ao diabo. A oração que Jesus ensinou pede que não entremos em tentação.',
  ),
  pack(
    'eternal',
    ['eternal life', 'everlasting life', 'vida eterna'],
    verses(['jhn', 3, 16], ['jhn', 17, 3], ['1jn', 5, 11], ['rom', 6, 23]),
    'Scripture says eternal life is in the Son, and that this is life eternal: to know the Father and Jesus Christ whom he sent. It is the gift of God, not the wage of sin. Read John 17 beside John 3.',
    'La Escritura dice que la vida eterna está en el Hijo, y que esta es la vida eterna: conocer al Padre y a Jesucristo, a quien él envió. Es la dádiva de Dios, no la paga del pecado. Lee Juan 17 junto a Juan 3.',
    'A Escritura diz que a vida eterna está no Filho, e que a vida eterna é esta: conhecer o Pai e a Jesus Cristo, a quem ele enviou. É o dom de Deus, não o salário do pecado. Leia João 17 junto de João 3.',
  ),
  pack(
    'judgment',
    [
      'judgment',
      'judgement',
      'judgment day',
      'when we die',
      'what happens when we die',
      'after death',
      'juicio',
      'dia del juicio',
      'cuando morimos',
      'que pasa cuando morimos',
      'despues de la muerte',
      'juizo',
      'dia do juizo',
      'quando morremos',
      'o que acontece quando morremos',
      'depois da morte',
    ],
    verses(['heb', 9, 27], ['jhn', 5, 24], ['rom', 14, 12], ['2co', 5, 10]),
    'Scripture says people die once, and after that the judgment. It also says whoever hears and believes the Son has passed from death to life and shall not come into condemnation. Each of us will give account. These verses are not a sentence on a person you name here.',
    'La Escritura dice que está establecido que las personas mueran una vez, y después el juicio. También dice que quien oye y cree al Hijo ha pasado de muerte a vida y no vendrá a condenación. Cada uno dará cuenta. Estos versículos no son una sentencia sobre alguien que nombres aquí.',
    'A Escritura diz que aos homens está ordenado morrerem uma vez, e depois o juízo. Também diz que quem ouve e crê no Filho passou da morte para a vida e não entrará em condenação. Cada um de nós dará conta. Estes versículos não são uma sentença sobre alguém que você nomeie aqui.',
  ),
  pack(
    'worship',
    ['worship', 'adoracion', 'adorar', 'adoracao', 'culto'],
    verses(['jhn', 4, 24], ['psa', 95, 6], ['rom', 12, 1], ['heb', 13, 15]),
    'Scripture says God is spirit, and those who worship him must worship in spirit and in truth. Worship is also presenting our bodies as a living sacrifice, and the sacrifice of praise. The psalm says to kneel before the Lord our maker.',
    'La Escritura dice que Dios es Espíritu, y que los que lo adoran deben adorar en espíritu y en verdad. La adoración también es presentar los cuerpos en sacrificio vivo, y el sacrificio de alabanza. El salmo dice que nos arrodillemos ante el Señor, nuestro hacedor.',
    'A Escritura diz que Deus é Espírito, e que os que o adoram devem adorar em espírito e em verdade. A adoração também é apresentar os corpos em sacrifício vivo, e o sacrifício de louvor. O salmo diz que nos ajoelhemos diante do Senhor, o nosso Criador.',
  ),
  pack(
    'obedience',
    ['obedience', 'obey', 'obediencia', 'obedecer'],
    verses(['jhn', 14, 15], ['1sa', 15, 22], ['jas', 1, 22], ['act', 5, 29]),
    'Scripture says those who love Jesus keep his commandments. To obey is better than sacrifice. James says be doers of the word, not hearers only. When men forbid what God commands, Peter says we ought to obey God rather than men.',
    'La Escritura dice que quien ama a Jesús guarda sus mandamientos. El obedecer es mejor que el sacrificio. Santiago dice que seamos hacedores de la palabra, no solo oidores. Cuando los hombres prohíben lo que Dios manda, Pedro dice que es necesario obedecer a Dios antes que a los hombres.',
    'A Escritura diz que quem ama a Jesus guarda os seus mandamentos. O obedecer é melhor do que o sacrifício. Tiago diz que sejamos praticantes da palavra, e não somente ouvintes. Quando os homens proíbem o que Deus manda, Pedro diz que é preciso obedecer a Deus antes que aos homens.',
  ),
  pack(
    'identity',
    [
      'identity',
      'who am i',
      'in christ',
      'identidad',
      'quien soy',
      'en cristo',
      'identidade',
      'quem sou',
      'em cristo',
    ],
    verses(['2co', 5, 17], ['jhn', 1, 12], ['eph', 2, 10], ['1pe', 2, 9]),
    'Scripture says if anyone is in Christ, he is a new creature. Those who receive him are given the right to become children of God. We are his workmanship, created for good works, and a people belonging to him. The name comes from him, not from this chat.',
    'La Escritura dice que si alguno está en Cristo, nueva criatura es. Los que lo reciben reciben el derecho de ser hechos hijos de Dios. Somos hechura suya, creados para buenas obras, y un pueblo que le pertenece. El nombre viene de él, no de este chat.',
    'A Escritura diz que, se alguém está em Cristo, nova criatura é. Os que o recebem recebem o direito de serem feitos filhos de Deus. Somos feitura dele, criados para boas obras, e um povo que lhe pertence. O nome vem dele, não deste chat.',
  ),
  pack(
    'loneliness',
    [
      'lonely',
      'loneliness',
      'i feel alone',
      'soledad',
      'me siento solo',
      'estoy solo',
      'sozinho',
      'me sinto sozinho',
      'solitario',
    ],
    verses(['deu', 31, 8], ['mat', 28, 20], ['heb', 13, 5], ['isa', 41, 10]),
    'Scripture says the Lord goes before you and will not leave you, and that Jesus is with his people always, even to the end of the age. He will never leave you nor forsake you. If the room is quiet, a local church is a place to be with people, not only with a verse.',
    'La Escritura dice que el Señor va delante de ti y no te dejará, y que Jesús está con los suyos todos los días, hasta el fin del mundo. No te dejará ni te desamparará. Si el cuarto está en silencio, una iglesia local es un lugar para estar con personas, no solo con un versículo.',
    'A Escritura diz que o Senhor vai adiante de você e não o deixará, e que Jesus está com os seus todos os dias, até o fim dos tempos. Ele não o deixará nem o desamparará. Se o quarto está em silêncio, uma igreja local é um lugar para estar com pessoas, não só com um versículo.',
  ),
  pack(
    'grief',
    ['grief', 'mourn', 'mourning', 'duelo', 'luto', 'lamento'],
    verses(['psa', 34, 18], ['mat', 5, 4], ['jhn', 11, 35], ['rev', 21, 4]),
    'Scripture says the Lord is near the brokenhearted, and that those who mourn shall be comforted. Jesus wept at the tomb of Lazarus. The last book says God will wipe away tears. Grief is not unbelief. Let your pastor sit with you in it.',
    'La Escritura dice que el Señor está cerca de los quebrantados de corazón, y que los que lloran serán consolados. Jesús lloró ante la tumba de Lázaro. El último libro dice que Dios enjugará toda lágrima. El duelo no es incredulidad. Deja que tu pastor se siente contigo en él.',
    'A Escritura diz que o Senhor está perto dos quebrantados de coração, e que os que choram serão consolados. Jesus chorou diante do túmulo de Lázaro. O último livro diz que Deus enxugará toda lágrima. O luto não é incredulidade. Deixe o seu pastor sentar-se com você nele.',
  ),
  pack(
    'comfort',
    ['comfort', 'depressed', 'depression', 'consuelo', 'depresion', 'desanimado', 'consolo', 'depressao', 'abatido'],
    verses(['mat', 11, 28], ['psa', 23, 1], ['2co', 1, 3], ['isa', 41, 10]),
    'Scripture invites the weary to come to Jesus and find rest. The psalm says the Lord is my shepherd. Paul calls God the Father of mercies and the God of all comfort. If the sadness is heavy, please talk with your pastor and with people in your local church. This chat is not a counselor.',
    'La Escritura invita al cansado a venir a Jesús y hallar descanso. El salmo dice que el Señor es mi pastor. Pablo llama a Dios Padre de misericordias y Dios de toda consolación. Si la tristeza pesa, habla con tu pastor y con personas de tu iglesia local. Este chat no es un consejero.',
    'A Escritura convida o cansado a vir a Jesus e achar descanso. O salmo diz que o Senhor é o meu pastor. Paulo chama Deus de Pai das misericórdias e Deus de toda consolação. Se a tristeza pesa, fale com o seu pastor e com pessoas da sua igreja local. Este chat não é um conselheiro.',
  ),
  pack(
    'guidance',
    [
      'guidance',
      "god's will",
      'will of god',
      'voluntad de dios',
      'vontade de deus',
      'direccion',
      'direcao',
    ],
    verses(['pro', 3, 5], ['psa', 32, 8], ['rom', 12, 2], ['jas', 1, 5]),
    'Scripture says to trust the Lord and not lean on your own understanding. He says he will instruct you in the way you should go. The will of God is discerned as the mind is renewed, and wisdom may be asked of him. These verses do not name the choice in front of you. Your pastor can help you read them beside it.',
    'La Escritura dice que confíes en el Señor y no te apoyes en tu propia prudencia. Él dice que te enseñará el camino en que debes andar. La voluntad de Dios se discierne cuando la mente se renueva, y la sabiduría se le puede pedir. Estos versículos no nombran la decisión que tienes delante. Tu pastor puede ayudarte a leerlos junto a ella.',
    'A Escritura diz que confie no Senhor e não se apoie no seu próprio entendimento. Ele diz que o instruirá no caminho que deve seguir. A vontade de Deus se discerne quando a mente se renova, e a sabedoria pode ser pedida a ele. Estes versículos não nomeiam a decisão que está diante de você. O seu pastor pode ajudar a lê-los ao lado dela.',
  ),
  pack(
    'return',
    [
      'second coming',
      'return of christ',
      'coming of the lord',
      'rapture',
      'segunda venida',
      'arrebatamiento',
      'volta de cristo',
      'arrebatamento',
      'vinda do senhor',
    ],
    verses(['act', 1, 11], ['1th', 4, 16], ['mat', 24, 44], ['rev', 22, 20]),
    'Scripture says this same Jesus will come in like manner as he was taken up, and that the Lord himself shall descend. He tells his people to be ready, because the hour is unknown. These verses do not set a date. Read them with your church, not as a calendar.',
    'La Escritura dice que este mismo Jesús vendrá como le vieron ir al cielo, y que el Señor mismo descenderá. Él dice a los suyos que estén preparados, porque la hora no se sabe. Estos versículos no ponen fecha. Léelos con tu iglesia, no como un calendario.',
    'A Escritura diz que esse mesmo Jesus virá do modo como o viram subir ao céu, e que o próprio Senhor descerá. Ele diz aos seus que estejam preparados, porque a hora não se sabe. Estes versículos não marcam data. Leia-os com a sua igreja, não como um calendário.',
  ),
  pack(
    'healing',
    ['healing', 'heal', 'healed', 'sanidad', 'sanar', 'sanidad', 'curar', 'cura divina', 'milagro', 'milagre', 'miracle'],
    verses(['jas', 5, 14], ['psa', 103, 3], ['mat', 4, 23], ['jer', 17, 14]),
    'Scripture tells the sick to call the elders of the church and pray, and it speaks of the Lord as the one who heals. Jesus healed in his ministry. These verses are not a diagnosis and not a treatment. For the body, see a doctor. For prayer, talk with your pastor.',
    'La Escritura dice al enfermo que llame a los ancianos de la iglesia y ore, y habla del Señor como quien sana. Jesús sanó en su ministerio. Estos versículos no son un diagnóstico ni un tratamiento. Para el cuerpo, ve a un médico. Para la oración, habla con tu pastor.',
    'A Escritura diz ao doente que chame os presbíteros da igreja e ore, e fala do Senhor como aquele que sara. Jesus curou no seu ministério. Estes versículos não são um diagnóstico nem um tratamento. Para o corpo, procure um médico. Para a oração, fale com o seu pastor.',
  ),
  pack(
    'abuse',
    ['oppression', 'oppressed', 'abuse', 'abuso', 'oprimido', 'opressao', 'violencia', 'violence', 'injusticia', 'injustica'],
    verses(['psa', 9, 9], ['psa', 34, 18], ['isa', 1, 17], ['psa', 82, 3]),
    'Scripture says the Lord is a refuge for the oppressed, and it tells God’s people to seek justice and relieve the oppressed. If someone is hurting you, tell your pastor and a person who can help you get safe. A verse is not a substitute for getting to safety.',
    'La Escritura dice que el Señor es refugio de los oprimidos, y pide al pueblo de Dios que busque el juicio y defienda al oprimido. Si alguien te está haciendo daño, díselo a tu pastor y a una persona que pueda ayudarte a estar a salvo. Un versículo no sustituye el ponerte a salvo.',
    'A Escritura diz que o Senhor é refúgio dos oprimidos, e pede ao povo de Deus que busque o juízo e socorra o oprimido. Se alguém está lhe fazendo mal, diga ao seu pastor e a uma pessoa que possa ajudar você a ficar em segurança. Um versículo não substitui o colocar-se em segurança.',
  ),
  pack(
    'trinity',
    ['trinity', 'trinidad', 'trindade', 'triune', 'godhead'],
    verses(['deu', 6, 4], ['mat', 28, 19], ['jhn', 1, 1], ['jhn', 14, 16]),
    'Scripture says the LORD is one. It also names the Father, the Son, and the Holy Spirit together, says the Word was God, and has Jesus ask the Father for another Comforter. Read these verses with your pastor. This note is not a creed written in place of them.',
    'La Escritura dice que el SEÑOR es uno. También nombra juntos al Padre, al Hijo y al Espíritu Santo, dice que el Verbo era Dios, y muestra a Jesús pidiendo al Padre otro Consolador. Lee estos versículos con tu pastor. Esta nota no es un credo escrito en lugar de ellos.',
    'A Escritura diz que o SENHOR é um. Também nomeia juntos o Pai, o Filho e o Espírito Santo, diz que o Verbo era Deus, e mostra Jesus pedindo ao Pai outro Consolador. Leia estes versículos com o seu pastor. Esta nota não é um credo escrito no lugar deles.',
  ),
  pack(
    'creation',
    [
      'creation',
      'creator',
      'created the world',
      'creacion',
      'creador',
      'quien creo',
      'criacao',
      'criador',
      'quem criou',
    ],
    verses(['gen', 1, 1], ['jhn', 1, 3], ['col', 1, 16], ['psa', 19, 1]),
    'Scripture opens with God creating the heavens and the earth. John says all things were made by the Word. Paul says all things were created by the Son and for him. The heavens declare the glory of God. The chapter is the account. This note does not add a second one.',
    'La Escritura abre con Dios creando los cielos y la tierra. Juan dice que todas las cosas fueron hechas por el Verbo. Pablo dice que todo fue creado por el Hijo y para él. Los cielos cuentan la gloria de Dios. El capítulo es el relato. Esta nota no añade otro.',
    'A Escritura abre com Deus criando os céus e a terra. João diz que todas as coisas foram feitas pelo Verbo. Paulo diz que tudo foi criado pelo Filho e para ele. Os céus declaram a glória de Deus. O capítulo é o relato. Esta nota não acrescenta outro.',
  ),
  pack(
    'purpose',
    [
      'purpose',
      'calling',
      'why am i here',
      'proposito',
      'llamado',
      'para que existo',
      'chamado',
      'por que existo',
    ],
    verses(['eph', 2, 10], ['mic', 6, 8], ['mat', 22, 37], ['1co', 10, 31]),
    'Scripture says we are God’s workmanship, created in Christ for good works he prepared. He asks us to do justly, love mercy, and walk humbly with him, and to love him with all the heart. Whatever you do, do it to the glory of God. That is the frame. It does not name your job for you.',
    'La Escritura dice que somos hechura de Dios, creados en Cristo para buenas obras que él preparó. Pide que hagamos justicia, amemos misericordia y caminemos humildemente con él, y que lo amemos con todo el corazón. Hacedlo todo para la gloria de Dios. Ese es el marco. No te nombra el oficio.',
    'A Escritura diz que somos feitura de Deus, criados em Cristo para boas obras que ele preparou. Ele pede que façamos justiça, amemos a misericórdia e andemos humildemente com ele, e que o amemos de todo o coração. Fazei tudo para a glória de Deus. Esse é o quadro. Ele não nomeia o seu ofício.',
  ),
  pack(
    'confession',
    ['confess', 'confession', 'confesar', 'confesion', 'confessar', 'confissao'],
    verses(['1jn', 1, 9], ['psa', 32, 5], ['jas', 5, 16], ['pro', 28, 13]),
    'Scripture says to confess sin to God, who is faithful to forgive, and to confess faults to one another and pray. The one who covers sin does not prosper. The one who confesses and forsakes it finds mercy. Confession is honest speech, not a show.',
    'La Escritura dice que confesemos el pecado a Dios, que es fiel para perdonar, y que nos confesemos las faltas unos a otros y oremos. El que encubre sus pecados no prosperará. El que los confiesa y se aparta hallará misericordia. La confesión es palabra honesta, no un espectáculo.',
    'A Escritura diz que confessemos o pecado a Deus, que é fiel para perdoar, e que confessemos as culpas uns aos outros e oremos. O que encobre os seus pecados não prosperará. O que os confessa e deixa alcança misericórdia. A confissão é fala honesta, não um espetáculo.',
  ),
  pack(
    'patience',
    ['patience', 'patient', 'longsuffering', 'paciencia'],
    verses(['gal', 5, 22], ['col', 3, 12], ['jas', 5, 7], ['eph', 4, 2]),
    'Scripture lists patience among the fruit of the Spirit. It tells the church to be patient, to wait as a farmer waits for rain, and to bear with one another in love. The Grow tab in this app walks through that fruit beside the verse.',
    'La Escritura pone la paciencia entre el fruto del Espíritu. Dice a la iglesia que se vista de paciencia, que sea paciente como el labrador que espera la lluvia, y que ande con paciencia, soportándose en amor. La pestaña Crecer de esta app recorre ese fruto junto al versículo.',
    'A Escritura põe a paciência entre o fruto do Espírito. Diz à igreja que se revista de paciência, que seja paciente como o lavrador que espera a chuva, e que ande com longanimidade, suportando-se em amor. A aba Crescer deste app percorre esse fruto junto do versículo.',
  ),
  pack(
    'fruit',
    [
      'fruit of the spirit',
      'fruits of the spirit',
      'fruto del espiritu',
      'frutos del espiritu',
      'fruto do espirito',
      'frutos do espirito',
      'kindness',
      'goodness',
      'faithfulness',
      'gentleness',
      'self-control',
      'self control',
      'temperance',
      'benignidad',
      'bondad',
      'fidelidad',
      'mansedumbre',
      'templanza',
      'benignidade',
      'bondade',
      'fidelidade',
      'mansidao',
      'dominio proprio',
    ],
    verses(['gal', 5, 22], ['gal', 5, 23]),
    'Scripture names the fruit of the Spirit in Galatians 5:22–23. The words follow the Bible you are reading. The Grow tab walks through each fruit with a few verses beside it.',
    'La Escritura nombra el fruto del Espíritu de un solo aliento. Las palabras siguen la versión que estás leyendo. La pestaña Crecer recorre cada fruto con unos versículos al lado.',
    'A Escritura nomeia o fruto do Espírito num só fôlego. As palavras seguem a versão que você está lendo. A aba Crescer percorre cada fruto com alguns versículos ao lado.',
  ),
  pack(
    'satan',
    ['satan', 'devil', 'lucifer', 'diablo', 'satanas', 'demonio'],
    verses(['jas', 4, 7], ['1pe', 5, 8], ['1jn', 3, 8], ['eph', 6, 11]),
    'Scripture says to submit to God and resist the devil, and that he will flee. Peter says the devil walks about as a roaring lion. The Son of God was manifested to destroy the works of the devil. Put on the whole armor of God. These verses warn and point to Christ. They are not a map of hidden powers.',
    'La Escritura dice que os sometáis a Dios y resistáis al diablo, y que huirá. Pedro dice que el diablo anda como león rugiente. El Hijo de Dios apareció para deshacer las obras del diablo. Vestíos de toda la armadura de Dios. Estos versículos advierten y señalan a Cristo. No son un mapa de poderes ocultos.',
    'A Escritura diz que vos sujeiteis a Deus e resistais ao diabo, e que ele fugirá. Pedro diz que o diabo anda como leão que ruge. O Filho de Deus se manifestou para desfazer as obras do diabo. Revesti-vos de toda a armadura de Deus. Estes versículos advertem e apontam para Cristo. Não são um mapa de poderes ocultos.',
  ),
]
